### ISSUE TITLE
Webstorm theme

### ISSUE THREAD

**Issue by nickroberts** [jesseweed/seti-ui#110]
I love the theme, and I use it (along with Seti Syntax) with Atom.

However, the powers that be would like me to use Webstorm (not a huge fan).

Is there any way we can port this to Webstorm, including the UI theme, syntax settings and icons?

Thanks!

**Comment by mikeerickson** [comment]
@nickroberts So, did you ever find a solution for this?

**Comment by ddennis** [comment]
bumping this thread since i am also looking for a solution.

**Comment by mikeerickson** [comment]
Spent time over weekend trying to get this working and appears to be related to issues with what version of Java is being used.

**Comment by jcirizar** [comment]
I need this too.

**Comment by mrosata** [comment]
Try here https://github.com/zchee/Seti_JetBrains/releases
