### ISSUE TITLE
SCSS syntax highlighting

### ISSUE THREAD

**Issue by dhenriet** [jesseweed/seti-ui#118]
Hi thanks for this great ST theme, I am just having a little problem with comments in .scss files. I have Syntax Highlighting for Sass (https://packagecontrol.io/packages/Syntax%20Highlighting%20for%20Sass) and Sublime text 3 build 3083 but can't have clean scss files highlighting.

![screenshot_1](https://cloud.githubusercontent.com/assets/4640027/6904448/1ac45092-d721-11e4-9bdc-8d1b4c4547ef.png)

![screenshot_2](https://cloud.githubusercontent.com/assets/4640027/6904422/fa87deac-d720-11e4-8766-103449bb7cd2.png)

**Comment by jhoell** [comment]
I'm having this same isse!

**Comment by seybsen** [comment]
+1
I always need to manually switch to "Syntax Highlighting for Sass" -> "SCSS" when opening .scss-files. I think in screenshots above sublime loaded the included syntaxhighlighting which comes with SetiUI.

**Comment by da-n** [comment]
Just discovered what was causing this bug after about a month of syntax highlight hell. No plans to fix this? I am having to simply remove Seti UI as a fix currently. Thanks.

**Comment by jesseweed** [comment]
Hey @da-n, @seybsen, @jhoell @dhenriet: sorry forgot about this one.

This is the repo for the Atom theme. Are you seeing this issue in Atom or Sublime?

**Comment by seybsen** [comment]
Oh, I'm sorry. I was talking about Sublime.

**Comment by dhenriet** [comment]
For me everything is working nice now, I remove sass plugin and install scss package plugin (https://packagecontrol.io/packages/SCSS). I set SCSS syntax in sublime + setUI.

![screenshot_4](https://cloud.githubusercontent.com/assets/4640027/9325499/0e7fa27e-4593-11e5-9d82-f6d1ab3b83a0.png)

![screenshot_5](https://cloud.githubusercontent.com/assets/4640027/9325531/40325c8a-4593-11e5-8d94-49939686f0ed.png)

**Comment by da-n** [comment]
@jesseweed apologies yes I was talking about Sublime Text as well, Dev Channel Build 3095 (on OS X v10.10.2). If there is anything else I can provide to help with issue please let me know. Thanks!

**Comment by jesseweed** [comment]
No worries, the seti port is maintained by @ctf0 over here: https://github.com/ctf0/Seti_ST3
