### ISSUE TITLE
TreeView icon doesn't display correctly after I upgraded to version 0.7.0

### ISSUE THREAD

**Issue by timnew** [jesseweed/seti-ui#172]
![screen shot 2015-05-04 at 12 45 03 pm](https://cloud.githubusercontent.com/assets/1287238/7448953/6b122600-f25b-11e4-953d-8796a6d37e7b.png)

**Comment by zetay** [comment]
atom -v 0.196.0
seti-ui 0.7.0
icon lost

**Comment by pitaj** [comment]
Same here

**Comment by jesseweed** [comment]
This is fixed in #173 and should be working now if you update to v0.7.1.

**Comment by pitaj** [comment]
@jesseweed - Thanks for the quick fix :)

**Comment by jesseweed** [comment]
No worries! Credit goes to @ccheney. I just broke it and then merged the fix :)
