### ISSUE TITLE
Request for seti-icon package

### ISSUE THREAD

**Issue by mrmckeb** [jesseweed/seti-ui#180]
I love the seti-syntax theme, and would like to use these icons with that theme. Is that something you're looking at releasing?

**Comment by wyze** [comment]
I actually had the same thought today. I just released a [seti-icons](https://atom.io/packages/seti-icons) package to Atom.

I hope this is alright with @jesseweed, if not, I will remove it.

**Comment by mrmckeb** [comment]
Thanks, great work @wyze.

**Comment by jesseweed** [comment]
Going to close this out as it looks like a package has already been created. Thanks @wyze!

**Comment by wyze** [comment]
No problem. Need to update it this week with all the hard work you put into 1.0. :)
