### ISSUE TITLE
SCSS Syntax Error Highlighting

### ISSUE THREAD

**Issue by Deorro** [jesseweed/seti-ui#193]
Hi.

Thank you for this great theme, I like a lot, but I have a small bug with syntax SCSS, I installed the plugin for SCSS and established that syntax, but only the colors of text for some parts of my code are shown, here I leave a screenshot:

![Screenshot](http://i.imgur.com/VkRQe6g.png)

How I can fix it, do I have to install another plugin ?.

Bye.

**Comment by jesseweed** [comment]
I've moved this over to the seti syntax repo: https://github.com/jesseweed/seti-syntax/issues/120
