### ISSUE TITLE
Sidebar color is not black like it was

### ISSUE THREAD

**Issue by kristjaningi** [jesseweed/seti-ui#199]
Somehow the black color in my sidebar changed to grey
Atom: 1.1.0
Seti: 0.8.0

<img width="630" alt="screen shot 2015-10-31 at 00 52 03" src="https://cloud.githubusercontent.com/assets/3003641/10860985/e8d29796-7f69-11e5-8d4f-c4482eb831c1.png">

**Comment by jonathandelgado** [comment]
To anyone having this issue, the following snippit in your styles.less file will fix this.

```
.tree-view-scroller {
	background: #101112 !important;
}
```

**Comment by kristjaningi** [comment]
Awesome! Thank you very much :smile:

**Comment by jonathandelgado** [comment]
@kristjaningi I think you should re-open this though, since this is ultimately an issue with the UI, that was just a temporary fix.

**Comment by jesseweed** [comment]
I actually just published the [0.8.1](https://github.com/jesseweed/seti-ui/releases/tag/v0.8.1) release which fixes the background issue so will go ahead and re-close. Cheers guys!
