### ISSUE TITLE
Cursor moves into the middle of the space character on indentations

### ISSUE THREAD

**Issue by revelt** [jesseweed/seti-ui#201]
The current Seti Syntax theme has problems with cursor positioning. Cursor moves OK between the letters within code's line, but not at the beginning of the line. The bug happens only on Seti theme, I just checked.

![Seti Theme Cursor Bug](http://i.imgur.com/AonHHZi.gif?1)

**Comment by karloluis** [comment]
What version of seti-ui are you using?

**Comment by revelt** [comment]
0.9.1, but now it looks OK, I just tested various files on latest Atom – all work fine. Closing the ticket now.
