### ISSUE TITLE
gulpfile toggle comment not working

### ISSUE THREAD

**Issue by hoyangtsai** [jesseweed/seti-ui#202]
When I write some gulpfile try to toggle some line as comment, it's not working.
I found out it's a theme issue that also occurs in another sublime theme.
To fix this, the scopeName of tmLanguage file needs to be modified.

Path: /Packages/Seti_ST3 package/icons/Langs/Gulpfile JS.tmLanguage
```XML
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
...
	<key>scopeName</key>
	<string>source.js, source.js.gulpfile</string>
</dict>
</plist>
```

YabataDesign/afterglow-theme#95

**Comment by jesseweed** [comment]
I have not been able to repro this, and I somewhat doubt it's caused by the theme, but feel free to re-open if you still see the issue.

**Comment by F1LT3R** [comment]
I also experience the same with with this theme, and also the afterglow theme. I am using the molokai colors (if that helps)
