### ISSUE TITLE
Possible to disable file icons in tabs?

### ISSUE THREAD

**Issue by SoulGit** [jesseweed/seti-ui#203]
Great theme! With many files open, the file icon becomes the only visible item in a tab, making tab identification difficult, if not impossible without toggling between them.  Is it possible to disable file icons in the tabs?

<img width="1408" alt="screen shot 2015-11-16 at 2 14 58 pm" src="https://cloud.githubusercontent.com/assets/1467796/11196557/976aff46-8c6c-11e5-8afe-553a05ec84ce.png">

**Comment by jesseweed** [comment]
It's not currently, no. But, I'm planning to add a config in the next version to make it a bit more customizeable (although with that many tabs open, you're only going to get 1-2 chars of the title anyway, which is likely not going to be much more useful).

**Comment by karloluis** [comment]
I think you are suffering from Chrome-titis. This many open tabs are only experienced by the most inflicted chrome users. But the feature would be nice.
