### ISSUE TITLE
Folder Name in Serif

### ISSUE THREAD

**Issue by mefynn** [jesseweed/seti-ui#207]
hey there, 
just noticed that the folder name is in serif while the rest is (@least) in sans.

besides that, i really love the ui and syntax! great job!

cheers

**Comment by revelt** [comment]
@mefynn is this still an issue? I don't see serifs on seti-ui (0.9.1) + Atom (1.5.3) left side Tree View, but maybe I'm looking at the wrong place? If you see serifs, can you clarify with a screengrab please?

**Comment by jesseweed** [comment]
I haven't seen any action on this for a while, so going to close it out.
