### ISSUE TITLE
Icons in tabs are truncated

### ISSUE THREAD

**Issue by alsoicode** [jesseweed/seti-ui#211]
First, I looooove this theme, so thank you. I've noticed an issue on Linux, specifically Ubuntu, in that icons in tabs are truncated. Only the right half of the icon is visible.

Example
![selection_013](https://cloud.githubusercontent.com/assets/86738/12484136/ca0381ec-c026-11e5-9e60-c72a8f0099eb.jpg)

**Comment by lanox** [comment]
i get that as well.

**Comment by alsoicode** [comment]
@lanox I had file-icons installed too. Disabling that package fixed the icon alignment. Thanks!
