### ISSUE TITLE
font size

### ISSUE THREAD

**Issue by seanmars** [jesseweed/seti-ui#214]
how do i change the font size and sidebar font color by myself?

**Comment by karloluis** [comment]
I don't have an answer to your question but maybe someone in the Atom slack channel can help you out with this. There is also documentation on Atom's site on how to make and modify themes. You are better of reading that and combing through the code.

**Comment by seanmars** [comment]
Thank you for your prompt reply.

**Comment by karloluis** [comment]
No problem. I really enjoy this theme, so I comb through the easier issues and try and help out.  If you find a solution be sure to post it and close the issue for future reference.
