### ISSUE TITLE
Could you please add Swift file icon?

### ISSUE THREAD

**Issue by yinanfang** [jesseweed/seti-ui#217]
I was using the [file-icons](https://github.com/DanBrooker/file-icons) packages and found that they've got some icon that seti-ui doesn't have. For example, the file icon for Swift. Could you please add it? Would it be possible for you to just merge some of their code?

**Comment by yinanfang** [comment]
I found that the file-icons are actually showing up on the tab but not in the file navigation on the left. It's probably a bug.
https://www.evernote.com/l/ABZmC2PRC59B3rcOhLNqu6RzLzfJdhVV7oM

**Comment by Alhadis** [comment]
@yinanfang Yes, there's currently a conflict. [I've submitted a PR](https://github.com/jesseweed/seti-ui/pull/216) that will help fix this, but the owner of this theme needs to merge it into upstream before it'll work.

**Comment by yinanfang** [comment]
@Alhadis Thank you so much for the pull request! I also noticed that the text on the tab is not vertically centered and the icon is half-covered. Do you know if it's a intended behavior or bug?
![settings_ __users_compass_code](https://cloud.githubusercontent.com/assets/4115566/13356951/ff373ac8-dc75-11e5-94f5-e66af6de2ccc.png)

**Comment by Alhadis** [comment]
@yinanfang That will also be fixed by the pull request. =)

**Comment by yinanfang** [comment]
@Alhadis Thank you so much for the help! I really appreciate that!
