### ISSUE TITLE
Add Additional File Icons

### ISSUE THREAD

**Issue by jesseweed** [jesseweed/seti-ui#231]
New file type icons to be added
- [x] php.inc #219
- [x] Swift #217
- [x] .gitattributes #210
- [x] C #205
- [x] C++ #205
- [x] Rust #200
- [x] gulpfile.babel.js #191
- [x] Grails #181
- [x] PerlScript #178 
- [x] ECMAScript #177 
- [x] Scale #117
- [x] Java ##39
- [x] SBT #117
- [x] jscs #105
- [x] jshint #104
- [x] direnv #103 
- [x] editorconfig #102 
- [ ] LaTeX #99  
- [x] Ocaml #98 
- [x] LiveScript #93
- [x] Vala #75
- [x] HackLang #69
- [x] Shell #66
- [x] Puppet #65 
- [x] Haskell #54 
- [x] Lua #48
- [x] Typescript #43
- [x] Go #43
- [x] C# #43
- [x] liquid #41
- [x] Haml #34
- [x] Media Files (audio, video, image)
- [x] Font Files

**Comment by jesseweed** [comment]
![icons](https://cloud.githubusercontent.com/assets/719964/14167141/005dd034-f6ce-11e5-987e-3206e53a059c.png)

**Comment by dsifford** [comment]
@jesseweed Would you be able to duplicate the `React.jsx` icon for TypeScript `.tsx` files on the 1.0 update? If so 👍

**Comment by jesseweed** [comment]
Sure, I don't see why not.

**Comment by dsifford** [comment]
Awesome, thanks. I've been doing it manually, but I figured I'd ask this time around.
