### ISSUE TITLE
Beta: Error badges background color same as text color

### ISSUE THREAD

**Issue by dsifford** [jesseweed/seti-ui#237]
![image](https://cloud.githubusercontent.com/assets/5240018/14939278/1c1a3a58-0f0e-11e6-8aad-e0f6e5b06b0c.png)

**Comment by jesseweed** [comment]
This should be fixed in the 1.0 update, let me know if you still see it.

**Comment by silvenon** [comment]
It's still there 😕

**Comment by dsifford** [comment]
Ditto @silvenon

**Comment by jesseweed** [comment]
Drats, you're right! I was looking in a file that had a different linter. On it...

**Comment by jesseweed** [comment]
Ok, this should be fixed in 1.0.2 update.

**Comment by silvenon** [comment]
Yay! Although I'm still confused about that blue oval (in this case it links to the ESLint rule).

<img width="301" alt="screen shot 2016-05-02 at 16 32 37" src="https://cloud.githubusercontent.com/assets/471278/14957076/9118b354-1083-11e6-896b-92b6a57f3655.png">

**Comment by jesseweed** [comment]
Hmm, I have't seen the 3rd one, I'll see if I can get it to pop-up.

**Comment by SaladFork** [comment]
I'm seeing similar with JSCS:

![](https://i.imgur.com/GUf8IP6.png)

With the inspector:

![](https://i.imgur.com/lpDhSjp.png)

It looks like `.badge` has both `color` and `background-color` set to the same value:

![](https://i.imgur.com/29Q9uBR.png)

```css
.badge {
    color: #519aba;
    background-color: #519aba;
}
```

**Comment by arturparkhisenko** [comment]
Also pls, dont forget about issues panel at the bottom:
![seti-ui-color-issue](https://cloud.githubusercontent.com/assets/139212/15039202/a9fd9510-12b3-11e6-962b-3df43e7f1984.png)
