### ISSUE TITLE
Request: Extend CSS icons to also include PostCSS SugarSS (.sss)

### ISSUE THREAD

**Issue by dsifford** [jesseweed/seti-ui#239]
If you haven't already noticed, I used lots of weird filetypes! 😂 

Could you also extend `.css` icons to include `.sss` on your next update?

 (here's the [sugarss repo](https://github.com/postcss/sugarss))

Thanks again. Awesome work! 👍

**Comment by jesseweed** [comment]
Added in 1.0.3
