### ISSUE TITLE
New UI breaks compatibility with the toolbar packages

### ISSUE THREAD

**Issue by cwilli34** [jesseweed/seti-ui#245]
Not sure if the [toolbar](https://atom.io/packages/tool-bar) package now needs to be updated, but the new UI does not work with the toolbar packages now.  The project heading in the tree view that should be inline with the tabs gets moved up a line, and then the toolbar is not visible.  So basically I can not use the toolbar package, and the toolbar-addons with the Seti-UI anymore.
![screenshot_20160502_111636](https://cloud.githubusercontent.com/assets/9610352/14958214/9fe85e06-1057-11e6-9401-65d853f4e37b.png)

**Comment by cwilli34** [comment]
And actually this only happens of course when the toolbar position is set to "top."  If I put the toolbar on the left or right hand side, the toolbar shows up fine.  Also, if I toggle the treeview, when it is not visible the toolbar will show up top also.  So the only time the toolbar does not show up is when it positioned on top when the treeview showing.

**Comment by rebornishard** [comment]
same here, need to edit it setting and remove padding

**Comment by jesseweed** [comment]
Sorry about that guys, didn't realize there was a toolbar package, or anything that went above the tabs. I believe PR #244 should fix this, I'll take a look at it now.

**Comment by jesseweed** [comment]
This should be fixed in 1.0.4, but the toolbar package doesn't show up at all for me regardless of theme, can somebody confirm before I close it out?

**Comment by jesseweed** [comment]
Confirmed working in 1.0.4

**Comment by cwilli34** [comment]
Working.  Thanks for the quick fix and turn around.
