### ISSUE TITLE
When i split panel, the new panel lost "compact mode" config

### ISSUE THREAD

**Issue by BrunoAzzi** [jesseweed/seti-ui#247]
Whe i split panel, the new panel does not is on compact mode, but the other panel still is in compact mode. If i turn off and on, then all the panels come back to normal. 
![screenshot from 2016-05-02 14-44-06](https://cloud.githubusercontent.com/assets/9367435/14962265/5d911594-1074-11e6-96de-c78f2189f086.png)

**Comment by jesseweed** [comment]
Hmm, that's an interesting one. I'll have to take a closer look...

**Comment by jesseweed** [comment]
I think I know what's going on here, I'll get a fix pushed out in the next update.

**Comment by jesseweed** [comment]
This should be fixed in the 1.1 update, let me know if you still see the issue.
