### ISSUE TITLE
Text & Icon not aligned

### ISSUE THREAD

**Issue by NerdPad** [jesseweed/seti-ui#248]
I noticed a couple of CSS issues with the new update:

- The Tab text, and Icons are misaligned, in both normal & compact mode.
- The JS icon is cut off from the bottom

![screen shot 2016-05-02 at 2 31 15 pm](https://cloud.githubusercontent.com/assets/87896/14963647/a80020a4-1072-11e6-803c-fa6226645657.png)

**Comment by jesseweed** [comment]
@NerdPad Are you using file-icons or any other icon package? This is only thing I've seen to cause this so far.

**Comment by NerdPad** [comment]
@jesseweed Yes, I had seti-icons installed previously. Uninstalled, and it's aligned properly now.

Thank you.

**Comment by NerdPad** [comment]
Noticed another issue. See how the selected db folder background overlaps the GIT icon?

The background highlight overlaps other items.

![screen shot 2016-05-02 at 3 09 29 pm](https://cloud.githubusercontent.com/assets/87896/14964818/feb03f9c-1077-11e6-858b-0af3f71aa697.png)

**Comment by jesseweed** [comment]
Seems to be a few bugs around compact mode. Thanks!

**Comment by ghs** [comment]
In my case, the X (close tab icon) for a modified and not saved file is moving up when the tab is hovered:

<img width="120" alt="captura de pantalla 2016-05-03 a las 10 53 16" src="https://cloud.githubusercontent.com/assets/94248/14978608/4b0b4a8a-111d-11e6-95bc-7ebfbf255ac2.png">

<img width="127" alt="captura de pantalla 2016-05-03 a las 10 49 20" src="https://cloud.githubusercontent.com/assets/94248/14978564/e7526ab4-111c-11e6-8404-9d8ff7fa326d.png">

**Comment by NerdPad** [comment]
@ghs I get that too

**Comment by jesseweed** [comment]
I believe the additional issues described are covered in #257 & #265. Closing out as the original issue seems to be resolved.
