### ISSUE TITLE
Tree view hiding tabs + not displaying right

### ISSUE THREAD

**Issue by ivirshup** [jesseweed/seti-ui#249]
This is sorta two issues? Maybe they're related.

Tree view's new header thing blocks tabs:
![screen shot 2016-05-02 at 2 55 56 pm](https://cloud.githubusercontent.com/assets/8238804/14964491/53c9c266-1076-11e6-853c-d2107f9f264c.png)
(there are tabs there I swear)

Also the header is displayed without actually showing the tree view

![screen shot 2016-05-02 at 2 55 24 pm](https://cloud.githubusercontent.com/assets/8238804/14964530/7caf8468-1076-11e6-9245-935eade8016a.png)

I'm on version 1.0.4 with Atom 1.7.3

Thanks!

**Comment by jesseweed** [comment]
Seems to be a bug with tree view on the right side. I think I have a fix.

**Comment by sboulkour** [comment]
I too have this issue, and also with tree view on the right side.

**Comment by jesseweed** [comment]
This should be fixed in the 1.1 update, let me know if you still see the issue.

**Comment by sboulkour** [comment]
Hi,

header is fixed, but not everything is working.
"Compact Mode" and "Hide tabs" options have no effects on the interface.

**Comment by jesseweed** [comment]
@sboulkour what version of Atom are running? Just to be safe, can you try reloading Atom after you update to latest Seti UI and see if that helps? I just tested with tree view on both left and right side and "compact mode" and " hide tabs" both do exactly what they should.

**Comment by sboulkour** [comment]
@jesseweed Atom 1.7.3, on MacOS X (El Capitan).
Restarting Atom fixed the issue, thx for the tip.

I see no other issue, so fix is fine to me. Thank you for the fix !

**Comment by ivirshup** [comment]
Works for me, thanks!
