### ISSUE TITLE
Compact mode > close icon in tab moves

### ISSUE THREAD

**Issue by quicoto** [jesseweed/seti-ui#257]
Hello,

I'm running **Atom 1.7.3** and **seti-ui 1.0.4**

Using compact mode the X icon on the tabs moved up. Shouldn't it appear in the same position as the blue circle?

Thank you very much

![seti-ui compact tabs icon](https://cldup.com/YMKSqS7Klh.gif)

**Comment by cwilli34** [comment]
Same here.
