### ISSUE TITLE
Tree view "current file" highlight hard to see

### ISSUE THREAD

**Issue by Leeds-eBooks** [jesseweed/seti-ui#258]
<img width="163" alt="screen shot 2016-05-03 at 13 01 46" src="https://cloud.githubusercontent.com/assets/4380655/14982602/664e053c-112f-11e6-9aef-b662c2994d4f.png">

The highlight telling me which file is currently selected (`esdoc.json`) is very hard to make out (it's just a slightly darker black) and it covers the top of the text of the filename beneath it (`ignore.coffee`).

**Comment by quicoto** [comment]
Agreed. I have two monitors, with the external one I can see ok because of the different contrast/brightness settings.

**Comment by jesseweed** [comment]
I didn't notice this on the laptop I usually develop on because I think it has higher brightness/contrast as @quicoto mentioned, but I did see the problem working on another machine the other day. I'll take a look at the PR and make sure this gets adjusted.
