### ISSUE TITLE
Fixed project name in sidebar works for one project, but not more

### ISSUE THREAD

**Issue by thomaslindstrom** [jesseweed/seti-ui#263]
The fixed project name in the sidebar is fixed and works well when there is only one project in the sidebar – but when you add more, you'd expect the project you're currently viewing in the tree view to be fixed above it.

![screen shot 2016-05-03 at 23 21 53](https://cloud.githubusercontent.com/assets/2833514/14998839/1778123e-1186-11e6-9adc-feab37d537b1.png)

[`position: sticky`](http://html5-demos.appspot.com/static/css/sticky.html) does not seem to be supported in Atom, yet, but that would fix this issue.

I'm on OS X, Atom v. 1.7.3 using seti-ui v. 1.0.3.

**Comment by chrisid** [comment]
+1

**Comment by jesseweed** [comment]
Yeah I was debating on the best way to handle this. It came down to either make none of them sticky, or only the top one, and decided since the majority of people only have one project folder (at least I do) I would go with the just first item sticky. I'll do some more playing with it though and see if I can come up with a solution that works.

**Comment by thomaslindstrom** [comment]
If it boils down to black/white have or don't have, in terms of UX, not having it when there's multiple project folders is definitely preferrable. I don't want to be confused with what folder I'm currently viewing.

I'm fairly certain that this problem can be solved neatly though.

**Comment by jesseweed** [comment]
Yeah I haven't spent much time on it (I honestly didn't know you could have multiple folders until about a week ago), so I'm sure there's a solution. Definitely open to ideas if anybody comes up with anything clever.

**Comment by thomaslindstrom** [comment]
Well, if you're using Safari; as mentioned: http://html5-demos.appspot.com/static/css/sticky.html
I'm pretty sure there's a polyfill for this functionality laying around somewhere.

**Comment by jesseweed** [comment]
Cool, I'll see if I can't get that to work in atom.

**Comment by thomaslindstrom** [comment]
Awesome. Let me know if I can help.

**Comment by jesseweed** [comment]
So just an update, I've disable the sticky header for the time being as there's a few other bugs with, and I didn't really like how it was implemented.

I'm going to leave this open though as I would like to revisit this later and bring the sticky header back.

If anybody finds a solution that works, please don't hesitate to submit a pull request to add it back in.

**Comment by thomaslindstrom** [comment]
Allright. What other bugs are you experiencing? I'll try and give this a shot later today.

**Comment by jesseweed** [comment]
Essentially using `position: fixed` as I had before means it breaks out out of the tree view container get 100% width of the window. Which is causing issues with things like moving tree view to the right side as the header essentially takes over the whole tab bar.

Obviously there's a better solutions, just haven't had a chance to really look at it. If you want to take a stab at it @thomaslindstrom, that'd be rad.

**Comment by thomaslindstrom** [comment]
In case you missed it, @jesseweed, I set up a pull request.

**Comment by jesseweed** [comment]
Brilliant, thanks @thomaslindstrom! Will push up an update today.

**Comment by thomaslindstrom** [comment]
Cool! Thanks.
