### ISSUE TITLE
Tree view "current file" highlight too tall in compact view

### ISSUE THREAD

**Issue by SaladFork** [jesseweed/seti-ui#265]
When in compact view, file rows are 25px tall but the highlight background is set to a height 35px which causes it to cut off the name of the following file:

![](https://i.imgur.com/sTkLzHp.png)

I've set it to red to be a bit more obvious:

![](https://i.imgur.com/YyAqqIW.png)

Removing `height: 35px;` from `atom-panel-container.left .entries.list-tree .directory.entry.list-nested-item.selected::before, atom-panel-container.right .entries.list-tree .directory.entry.list-nested-item.selected::before, atom-panel-container.left .entries.list-tree .file.entry.list-item.selected::before, atom-panel-container.right .entries.list-tree .file.entry.list-item.selected::before` seems to fix it.

**Comment by jesseweed** [comment]
Good catch, I'll add this to my list of compact mode bugs...

**Comment by jesseweed** [comment]
This should be fixed in the 1.1 update, let me know if you still see the issue.

**Comment by SaladFork** [comment]
@jesseweed: The height looks to be correct but it is now vertically offset too low:
![](https://i.imgur.com/GbLsVtC.png)

**Comment by SaladFork** [comment]
@jesseweed Can this be reopened for the above issue? Would you prefer another issue be filed for the offset?
