### ISSUE TITLE
Dragging tabs in compact view shows a too-large placeholder

### ISSUE THREAD

**Issue by SaladFork** [jesseweed/seti-ui#266]
This one is difficult to get a screenshot off, but when dragging tabs to reorder them, a vertical blue line is shown where the tab will end up. When in compact view, the vertical blue line is too tall for the tabs (seems to be the height of the non-compact tabs).

**Comment by petemill** [comment]
Here's the screenshot:
![image](https://cloud.githubusercontent.com/assets/741836/15032357/dafa5ec2-1214-11e6-9d43-00567de7664a.png)
