### ISSUE TITLE
Custom icons' padding is bigger than the one for original icons.

### ISSUE THREAD

**Issue by yupswing** [jesseweed/seti-ui#270]
I think the padding between files is way too big when using custom icons.
I work on a 13'' screen and I really like the custom icons (especially the color points me immediately to the right file in a folder).
But since the padding adds up for every file on the custom icons, it ends up wasting a lot of precious vertical space.
Could it be the same padding as the original icon?
Btw, thanks a lot for the theme (and I love the last update)

![Example](https://dl.dropboxusercontent.com/u/683344/temp/atom-icons.png)

**Comment by jesseweed** [comment]
@yupswing you should be able to select "compact mode" in the theme setting and get back to the old padding size. Let me know if that doesn't work for you.

**Comment by yupswing** [comment]
The picture I've posted is ALREADY compact mode.
The normal mode is even MORE padded.

I think the files' vertical padding (the folders are allright) should be less to match the padding in NORMAL mode.
It makes sense to have it the same with custom icons or without them.

Sorry, this is a very little issue, but it matters a lot for people like me with small screens where every pixel is worth.

![Icons padding showing off](https://dl.dropboxusercontent.com/u/683344/temp/atom-icons2.jpg)

**Comment by yupswing** [comment]
@jesseweed sorry to bother you, should this issue be reopen? otherwise sorry for the hassle.
