### ISSUE TITLE
vertical scrollbar so thin I can't grab it with mouse

### ISSUE THREAD

**Issue by jamr-ron** [jesseweed/seti-ui#271]
Video attached, latest version of atom
[___seti.zip](https://github.com/jesseweed/seti-ui/files/253064/___seti.zip)

**Comment by jamr-ron** [comment]
Any chance you could make the vertical scrollbar for the sidebar width adjustable in your settings page? I love the work you've done with your theme, but I've been unable to use it as I can't grab the scrollbar. A good sized one is the "Atom Material" theme. Your work with setting up icons for all the file types definitely is helpful!

**Comment by captain-awesome** [comment]
go to `theme settings`.
where it says __(?) you can also style atom by editing `your stylesheet`__  towards the top, select `your stylesheet`. this will open your `.atom` stylesheet settings.

you want to open `packages\seti-ui\styles\scrollbars.less`.
increase the width size to whatever you like.
i have mine set to `width: 11px;`; anything less than that doesn't seem to work.

please know that future updated of this theme will revert your changes.

hope this helps

**Comment by PwrSrg** [comment]
Same issue here.  Great theme, but completely useless if I can't scroll to reach my files!

![untitled-1](https://cloud.githubusercontent.com/assets/711603/15755621/3e21cad4-28c3-11e6-8a94-6a7c69fc37e0.png)

**Comment by captain-awesome** [comment]
hi pwrsrg,
what i posted above should resolve your issue for now.
hopefully @jesseweed takes notice of this thread.

**Comment by jesseweed** [comment]
Hey guys, so it seems no matter what I do I can't make any change to the scrollbars on Mac. I went ahead though and just copied in the scrollbar styles from Atom Material since report is those work ok.

Let me know if that makes it any better or not once you update to 1.3.
