### ISSUE TITLE
Theme color issues after updating to v1.1.2 

### ISSUE THREAD

**Issue by TerrenceLJones** [jesseweed/seti-ui#274]
After updating to v1.1.2 my theme color setting was lost. I went to the package settings and notice that the theme was still set to my desired setting. However, it was actually displaying incorrectly. After changing to a different setting and then back to my desired one, it was shown correctly. Just wanted to let you all know. Thanks!

**Comment by TerrenceLJones** [comment]
Also it appears that the Compact mode feature is broken. I'm toggling between on and off and not seeing a difference in the display.

**Comment by TerrenceLJones** [comment]
Ok, after a full reload of Atom everything appears to be working correctly. Just for my information is it expected behavior to have to reload or close/reopen the IDE for the package/theme update to function correctly?

**Comment by jesseweed** [comment]
Not usually, but occasionally something stuck and doesn't refresh quite right during an update.

**Comment by TerrenceLJones** [comment]
Ok thanks.
