### ISSUE TITLE
Disable Animations setting description is ambiguous

### ISSUE THREAD

**Issue by jeffschwartz** [jesseweed/seti-ui#275]
Should read as
`"Disable Animations"/ "Check this if you want to disable animations"`
or
`"Enable Animations"/ "Check this if you want to enable animations"``

The way it is currently worded is ambiguous as to the intention of the checkbox and what its default state is.

![screen shot 2016-05-10 at 1 44 49 pm](https://cloud.githubusercontent.com/assets/271288/15156567/a026f4e0-16b5-11e6-998f-971722024a86.png)

**Comment by jesseweed** [comment]
Oh you're right that is worded strangely. I'll fix.

**Comment by jesseweed** [comment]
This is fixed as of 1.2.2.
