### ISSUE TITLE
Compact Mode doesn't work cleanly

### ISSUE THREAD

**Issue by hylaride** [jesseweed/seti-ui#276]
Compact mode still leaves large font sizes on the project folder pane. Interestingly, the top listed project shrinks.

Here's a screenshot (notice the top left project folder is "compact" and the others aren't):
<img width="1452" alt="screenshot" src="https://cloud.githubusercontent.com/assets/17935338/15167876/64e362fc-16fa-11e6-97c1-2120a7c969d5.png">

**Comment by hylaride** [comment]
Realized I should've added a screenshot! :)

**Comment by jesseweed** [comment]
Ooooh! I see what you're saying now :)

Weird, I'll take a look.

**Comment by hylaride** [comment]
Thanks so much!  Other than the super sizing, I love the new theme! 👍

**Comment by ivanakimov** [comment]
Actually, compact mode stopped working for me completely. Just updated to 1.1.2.

**Comment by jesseweed** [comment]
@ivanakimov out of curiosity have yo tried restarting atom? Seems to be an issue in several themes with things not refreshing properly after updating.

**Comment by ivanakimov** [comment]
@jesseweed I haven't. But you're right, as soon as I restarted Atom, compact mode worked! Thank you :]

**Comment by jesseweed** [comment]
Sounds like this was fixed by a restart. Feel free to re-open if you still experience issues.

**Comment by hylaride** [comment]
A restart fixed it for ivanakimov, but not for the issue that I opened...

**Comment by ivanakimov** [comment]
Sorry, I kind of hijacked this thread.

**Comment by hylaride** [comment]
Ah, the 1.2.2 update seems to have fixed it! Thanks!
