### ISSUE TITLE
Compact mode does not apply to split panes

### ISSUE THREAD

**Issue by TylerRockwell** [jesseweed/seti-ui#278]
When splitting panes in Atom, the original pane stays in compact mode, but any splits have the non-compact styling.

<img width="1674" alt="screen shot 2016-05-10 at 5 21 17 pm" src="https://cloud.githubusercontent.com/assets/13321905/15162924/ad339f1c-16d3-11e6-8b9a-76b6ebc13c4c.png">

Disabling and re-enabling compact mode seems to resize all the tabs properly, but is impractical to do every time.

**Comment by jesseweed** [comment]
@TylerRockwell: What version of Seti are you running? This should have been fixed in the 1.1 update last night.

If you are running 1.1, try and restart Atom and see if that fixes it. I've heard a few reports of the theme not refreshing properly after update.

**Comment by TylerRockwell** [comment]
I did not have the 1.1 update. Just installed it and the issue is resolved. Thanks for all your hard work on this UI @jesseweed .
