### ISSUE TITLE
New update doesn't support old icon

### ISSUE THREAD

**Issue by frankn11** [jesseweed/seti-ui#279]
I have noticed that the Scss and Ruby icon have changed. I doubt they are the new official.

**Comment by frehner** [comment]
In addition, the previous update had the correct icon for .liquid files. Now the icon is a pair of keys.

**Comment by frehner** [comment]
Actually, a complete restart of Atom appears to have resolved this issue for me.

**Comment by frankn11** [comment]
Yes it does, thx for the reply!
