### ISSUE TITLE
Can't install in latest version of atom

### ISSUE THREAD

**Issue by leetrout** [jesseweed/seti-ui#280]
Using  Atom 1.2.4 when I search for "seti ui" in themes I see a red warning message and no install button. The warning message reads

```
There's no version of this package that is compatible with your Atom version. The version must satisfy >1.7.0
```

**Comment by jesseweed** [comment]
Are you running the latest version of Atom?

**Comment by jesseweed** [comment]
Oh sorry, your using 1.2.4, try and update if you can the latest update of only tested on 1.6+

**Comment by leetrout** [comment]
Oh I thought I was. It wasn't clear from that error message that atom was
what was out of date... I thought it auto updated. I'll update later when
I'm finished working for the day. Thanks.

**Comment by jesseweed** [comment]
Going to close this out. Feel free to re-open is you still have trouble after updating.

**Comment by avabinary** [comment]
hi, i've reopened this since I ran into this problem

```No available version compatible with the installed Atom version: 1.6.2```

apm update && apm upgrade both ran successfully
