### ISSUE TITLE
Height Inconsistencies in compact mode.

### ISSUE THREAD

**Issue by NerdPad** [jesseweed/seti-ui#283]
I have compact mode on, and I have couple of issues.

- The root folder (Project/Header?) height is too large. In the previous version the height of the root folder height wasn't this big. Compact mode hardly makes any difference in the new theme.

- There gap between folder, and files are inconsistent with custom icons are selected

And the height is inconsistent.
No Custom Icons:
![screen shot 2016-05-16 at 5 52 38 pm](https://cloud.githubusercontent.com/assets/87896/15305105/26850e4a-1b8f-11e6-8843-44431fc882e6.png)

With Custom Icons
![screen shot 2016-05-16 at 5 52 50 pm](https://cloud.githubusercontent.com/assets/87896/15305116/3358d476-1b8f-11e6-8336-4dcb069153cf.png)

I think compact mode should have the same dimensions as the previous theme had, and non-compact mode can be bigger, and bolder for ppl that like it.

**Comment by jesseweed** [comment]
This should be fixed in 1.2.1 update. Feel free to re-open is you still have an issue.
