### ISSUE TITLE
Hotkey for showing tab bar

### ISSUE THREAD

**Issue by cortner** [jesseweed/seti-ui#284]
is it possible to add a hot-key for showing / hiding the tab-bar? 
Thanks,

**Comment by jesseweed** [comment]
I debated adding hot keys, haven't decided whether it's a good idea or not yet. Will consider it.

**Comment by Leeds-eBooks** [comment]
e.g. https://atom.io/packages/tab-toggler I personally think this should remain the responsibility of separate packages, rather than bloating this UI theme with keybindings

**Comment by cortner** [comment]
Fine for me thanks for point it out.
