### ISSUE TITLE
Compact Mode - Status Bar and Fonts

### ISSUE THREAD

**Issue by OwenMelbz** [jesseweed/seti-ui#287]
Hey, previously in 0.9 versions the status bar was compact and took up minimal space, however with the introduction of "styles/status-bar.less" this makes the bars much larger - especially when plugins are enabled.

For example see the 2 below screen shots - 1 screenshot is taken with "styles/status-bar" included and 1 is without.

Here is with the file included

![settings_ __users_owen_sites_indigo-swan](https://cloud.githubusercontent.com/assets/1094740/15358857/769046b4-1cfe-11e6-93f4-ad94940eec5e.png)

As you can see its very large and bulky, when i remove the file it tightens up and is once again "compact"

![settings_ __users_owen_sites_indigo-swan](https://cloud.githubusercontent.com/assets/1094740/15358823/429d2c82-1cfe-11e6-91ac-6b99ad81836b.png)

You'd expect with the "Compact Mode" toggle in the settings it to be compact again, would we be able to get this sorted in a future release?

Additionally the introduction of the enforced fonts have bloated the sidebars and file tree, again "Compact Mode" does not effect this.

New Font ->

![settings_ __users_owen_sites_indigo-swan](https://cloud.githubusercontent.com/assets/1094740/15358976/fae25aa6-1cfe-11e6-8a6e-d9e3f08d75bb.png)

Old Font ->

<img width="325" alt="settings_ __users_owen_sites_indigo-swan" src="https://cloud.githubusercontent.com/assets/1094740/15359050/6061a620-1cff-11e6-95c0-38949b0217b2.png">

As you can see - the latest updates make the whole application a lot more bulky - is there anyway to either overwrite this to be more compact, or make sure the Compact Setting in Prefs affects a little more, as for developers on the go with smaller devices are going to have a whole lot of their screen taken up by whats effectively padding.

Thank you :)

**Comment by jesseweed** [comment]
Hey @OwenMelbz, have a look at the 1.2 update, should address most of the concerns. Icon padding is reduced, and status bar padding is removed.

As for the font, there are 2 options available in settings. Roboto, or whatever the default Atom font is. I reworded the option so it's more obvious. Instead of "SF UI Text" (the current Atom default), it now says "Default Atom Font"

**Comment by jesseweed** [comment]
Going to close this out. You can re-open if you still have issues.
