### ISSUE TITLE
Padding and fonts very large in "Project Find Results" view

### ISSUE THREAD

**Issue by sirianni** [jesseweed/seti-ui#289]
Even when enabling "compact mode" the fonts and padding are very large in the Project Find Results view. It was much more compact prior to the Seti UI refactoring.  It is much larger than the atom builtin themes.
 
![selection_003](https://cloud.githubusercontent.com/assets/381302/15555665/bcfbd548-2297-11e6-83c5-37c515de115e.png)

**Comment by jesseweed** [comment]
As of v1.2.3 compact mode now applies to project find view. Feel free to re-open if you still find issues.
