### ISSUE TITLE
Same color for background and font in settings

### ISSUE THREAD

**Issue by almadsen** [jesseweed/seti-ui#291]
I get the same color on the background and on the font in settings in Mininmap:

![skarmavbild 2016-05-26 kl 10 27 58](https://cloud.githubusercontent.com/assets/1423040/15569007/351be0b2-232f-11e6-98ec-2bb219786718.png)

**Comment by jesseweed** [comment]
@almadsen try updating to the latest version of minimap. This fixed the issue for me. Feel free to re-open if it doesn't.

**Comment by almadsen** [comment]
Did update, Mininmap & seti-ui, still a bugg.
