### ISSUE TITLE
Custom styles don't update when opening Atom

### ISSUE THREAD

**Issue by kand** [jesseweed/seti-ui#292]
I have Seti-UI theme color set to Purple, which appears to change Atom's styleguide colors such as `@background-color-selected` to purple which I'm using in my custom styles to color tree view.

However, until I reopen my styles.less and save it, treeview uses the Seti-UI default Blue theme colors instead of the purple defined by `@background-color-selected`.

Theorizing here, but could this have something to do with styles.less loading up before Seti-UI has fully changed the theme to Purple?

**Comment by jesseweed** [comment]
I believe this has be fixed. Feel free to re-open if you still experience this issue.
