### ISSUE TITLE
Apple icon is shown for all header files

### ISSUE THREAD

**Issue by mcurreri** [jesseweed/seti-ui#294]
I looked though the source code and noticed the apple logo is used for any .h filename extension. I'm not sure if this was a design choice but it seems strange to associate all header files with apple/objective C. Perhaps an H icon in the same format as the C icon would be more universal?

![seti_icon_discrepency](https://cloud.githubusercontent.com/assets/8471684/15615451/81a67acc-240c-11e6-89f3-85ceca7e3b4b.PNG)

**Comment by bsnsk** [comment]
Same problem here

**Comment by jesseweed** [comment]
Updated .h and .m files to use c icon in latest v1.2.3
