### ISSUE TITLE
autocomplete-go highlighting and project manager

### ISSUE THREAD

**Issue by vokary** [jesseweed/seti-ui#296]
Hello,

I have found two issues with the latest ui and syntax version
seti-syntax@1.0.1
seti-ui@1.2.3
- autocomplete-go
  it's not possible to read the text
- project-manager
  when the file in project-manager is selected it hides part from autocomplete

![Image](http://i.imgur.com/L94UzqC.png)

![Image](http://i.imgur.com/zr4tlFS.png)

**Comment by spalonytoster** [comment]
I got the same problem.

**Comment by moberemk** [comment]
This issue affects me too; you can circumvent it by moving the highlight off the option you want to select, but when you only have one option on the list it's impossible to read. I've had to stop using the theme because of this issue.

**Comment by SandyFigueroa** [comment]
Hey, i got the same problem.

**Comment by jesseweed** [comment]
I believe this has been fixed a few updates back. Feel free to re-open if you still experience issues. Thanks!
