### ISSUE TITLE
Background color of overwritten keybindings

### ISSUE THREAD

**Issue by Zeroji** [jesseweed/seti-ui#297]
Installed theme yesterday, noticed this issue today:

Keybindings page with Seti (any color):
![http://i.imgur.com/k5GWyCV.png](http://i.imgur.com/k5GWyCV.png)

Same page with default Atom Dark theme:
![http://i.imgur.com/W1N8bIw.png](http://i.imgur.com/W1N8bIw.png)

Overwritten keybindings are highlighted, and somehow the text isn't readable at all (unless selected manually)
I'm using Seti 1.2.3 and Atom 1.7.4.

**Comment by jesseweed** [comment]
This is fixed in 1.3 update.
