### ISSUE TITLE
Any file name with 'license' will show the license icon instead of the language icon

### ISSUE THREAD

**Issue by wellsonjain** [jesseweed/seti-ui#300]
![screen shot 2016-06-02 at 11 56 52 am](https://cloud.githubusercontent.com/assets/5293612/15731562/8e552ef6-28b9-11e6-81b4-0dfcdc58941e.png)

As you can see, it shows wrong file icon since the file name contains 'license'.

Atom version: 1.7.4
Seti UI version: 1.2.3
OS: Mac OS 10.11.5

**Comment by jesseweed** [comment]
I went ahead and updated so the only file that gets license icon for now is a `LICENSE` file. Cheers!
