### ISSUE TITLE
Bottom atom-panel left behind after closing

### ISSUE THREAD

**Issue by UkTails** [jesseweed/seti-ui#305]
I'm not sure whether this is a bug with the theme or with Emmet (as I'm using the bottom panel with Emmet), but this doesn't seem to happen with other themes.

When I use the bottom panel, and close it, it leaves behind a boarder where the panel was. And the more panels you open, the more it leaves behind. Hopefully the pictures demonstrate that a little better:

![screen shot 2016-06-08 at 20 44 13](https://cloud.githubusercontent.com/assets/8030370/15908568/4d225c82-2dba-11e6-92aa-f5790b4e7ab4.png)
![screen shot 2016-06-08 at 20 45 03](https://cloud.githubusercontent.com/assets/8030370/15908580/566903a4-2dba-11e6-8401-5d55dd448ee6.png)

**Comment by stream7** [comment]
I'm not using emmet and I can confirm this is happening when I search for something but no match is found. See https://cl.ly/2n0z0T2s1A1f

**Comment by jesseweed** [comment]
I believe this has be fixed. Feel free to re-open if you still experience this issue.

**Comment by stream7** [comment]
@jesseweed still getting this 🤔 

![index_js_ ___code_citrusbyte_att-iot-platform-console](https://cloud.githubusercontent.com/assets/301259/24866655/781e9a50-1e13-11e7-9c69-be1d10f6ea0a.png)

**Comment by jesseweed** [comment]
@stream7 can you confirm you have the latest versions of both Atom and Seti?

**Comment by stream7** [comment]
I think I do.

Atom `1.15.0`
`seti-ui` `1.7.0`
`seti-syntax` `1.1.3`
