### ISSUE TITLE
Footer not displayed correctly

### ISSUE THREAD

**Issue by AntunBartonicek** [jesseweed/seti-ui#306]
When using Seti theme footer isn't displayed on top of other elements so it doesn't behave as standard theme.
Caused by recent update (both Atom and Seti had updates so not sure which one caused it).
Pictures will probably explain the issue better (area marked with red rectangle):
Atom theme:
![atomdark](https://cloud.githubusercontent.com/assets/19833052/15922060/0b06553a-2e26-11e6-8383-04d6944198c3.jpg)
Seti:
![seti](https://cloud.githubusercontent.com/assets/19833052/15922059/0b05f392-2e26-11e6-98a1-ded56dd7f52b.jpg)

**Comment by jesseweed** [comment]
I believe this has be fixed. Feel free to re-open if you still experience this issue.
