### ISSUE TITLE
Search for this topic on the topic of atom, when you click on the install

### ISSUE THREAD

**Issue by pmnote** [jesseweed/seti-ui#311]
There’s no version of this package that is compatible with your atom version. The version must satisfy >1.8.0.

No available version compatible with the installed Atom version: 1.5.3

**Comment by spaceporn** [comment]
There are two comments on the commit (7e04add769795cf8a3fbd60f7ea208f6f2fe7d25) that is causing this, one from 13 and the other from 2.

https://github.com/jesseweed/seti-ui/commit/7e04add769795cf8a3fbd60f7ea208f6f2fe7d25#commitcomment-18187345
https://github.com/jesseweed/seti-ui/commit/7e04add769795cf8a3fbd60f7ea208f6f2fe7d25#commitcomment-18059467

It's just a matter of replacing `>` with `>=`.
