### ISSUE TITLE
Selected text is of same color as highlight

### ISSUE THREAD

**Issue by MayasHaddad** [jesseweed/seti-ui#312]
![9wzqrubinj](https://cloud.githubusercontent.com/assets/1893921/16816263/7ce2c1de-493d-11e6-8317-bc3fc270791f.gif)

p.s. I really love this theme, great job 👍

**Comment by captain-awesome** [comment]
Did you manage to get your issue resolved? If so can you please explain how?
@jesseweed - Please advise on how to modify the selection color?

**Comment by jesseweed** [comment]
This should be fixed. Feel free to re-open if you still experience this issue.
