### ISSUE TITLE
gulpfile and gruntfile icon not rendered properly

### ISSUE THREAD

**Issue by kkoo95** [jesseweed/seti-ui#314]
Both kinds of files were rendered as JS files. I had to modify Gulpfile JS and Gruntfile _.tmLanguage_ files to make it work:

**from**
    `<string>source.gulpfile.js, source.js</string>`
**to**
    `<string>source.js, source.gulpfile.js</string>`

Same kind of fix for gruntfile.

Is it a real bug or is it just me ? I notice npm settings are already "correctly" written.

**Comment by jesseweed** [comment]
I believe this should be fixed, but feel free to re-open if not.
