### ISSUE TITLE
Too much padding in tabs

### ISSUE THREAD

**Issue by slikts** [jesseweed/seti-ui#315]
The tab bar becomes less and less usable with the number of tabs; at the minimum it will be 2/3rds white space with just the X button, and before that 3/5ths white space with just the icon and X button. The white space should not be prioritized over the icon or title. This is a very frustrating oversight in the theme.

This is with "Compact Mode" enabled.

**Comment by jesseweed** [comment]
Hopefully this has been addressed in the last few updates.
