### ISSUE TITLE
Icons for Vue.js files

### ISSUE THREAD

**Issue by ErickPetru** [jesseweed/seti-ui#316]
[Vue.js](http://vuejs.org) Single File Components (`.vue` extension) should be supported, the SVG icon already exists: https://commons.wikimedia.org/wiki/File:Vue.js_Logo.svg.

**Comment by bstrahija** [comment]
+1

**Comment by imjakechapman** [comment]
+1

**Comment by dzift** [comment]
+1

Was surprised to see it's not supported yet.
