### ISSUE TITLE
Request: Add an icon for Dart files

### ISSUE THREAD

**Issue by DanTup** [jesseweed/seti-ui#325]
I really like this theme in VS Code, but the lack of a Dart icon makes me sad :(

The official images are here https://github.com/dart-lang/logos

**Comment by lucafaggianelli** [comment]
Yeah it would be nice to have icons for .dart and pubspec.yaml

**Comment by DanTup** [comment]
Fixed in 058cdb2 (see https://github.com/jesseweed/seti-ui/pull/525).
