### ISSUE TITLE
UI Bug with Multi-Row Tabs Package

### ISSUE THREAD

**Issue by TwoLikeYou** [jesseweed/seti-ui#326]
When using multi-row tabs (https://atom.io/packages/multirow-tabs) with Seti-ui, the second (and consecutive rows) do not display properly.  Sometimes one tab in the row shows, other times none.
See the 'floating' changelog tab in the following screenshot:
<img width="959" alt="screen shot 2016-09-08 at 3 52 33 pm" src="https://cloud.githubusercontent.com/assets/2001698/18369795/bcbb4cd8-75dc-11e6-9f16-b69f8351a75f.png">

This issue does not occur when using the built-in atom themes.  Here is Atom Dark:
<img width="957" alt="screen shot 2016-09-08 at 4 01 50 pm" src="https://cloud.githubusercontent.com/assets/2001698/18369976/1a28ab3a-75de-11e6-8540-9a5419d9382b.png">

Some investigation showed that the following causes the issue:
`atom-workspace.seti-compact atom-workspace-axis.vertical .tab-bar {
    height: 40px;
}`

and changing height to auto (same as the Atom Dark theme) in my local styles file resolved the display problem:

`atom-workspace.seti-compact atom-workspace-axis.vertical .tab-bar {
    height: auto;
}`

<img width="955" alt="screen shot 2016-09-08 at 4 04 30 pm" src="https://cloud.githubusercontent.com/assets/2001698/18369989/251b09ac-75de-11e6-937c-63b9935db04b.png">

Please let me know if I can provide any more helpful info.

**Comment by jesseweed** [comment]
Hmm, interesting. I actually hadn't heard of that package. Thanks for the info, I will look into a fix.

**Comment by jesseweed** [comment]
This plugin only has 3k downloads in the last 2 years, closing this as not worth the effort. Feel free to add a PR to update support for this package if still needed.

**Comment by ardentbriar** [comment]
Just published [`manytab`](https://atom.io/packages/manytab), it makes multiline tabs work with Seti.

![seti](https://user-images.githubusercontent.com/67130289/85171033-c8df4700-b25d-11ea-96cb-5d51a7407d35.png)
