### ISSUE TITLE
Seti things all projectfiles are ignored files.

### ISSUE THREAD

**Issue by jonathan-dejong** [jesseweed/seti-ui#335]
Hi,

So I'm using VVV (https://github.com/Varying-Vagrant-Vagrants/VVV/) and when adding wordpress-default (default WordPress installation included with VVV) Seti (or possibly atom) consider it just a folder rather than a project and all files (.php, .css etc.) are regarded as ignored files. 

To replicate:
1. Get VVV running
2. Have Seti and Project Manager packages installed. 
3. With an empty editor, Go to File > Add project folder.
4. Add the folder VVV/www/wordpress-default.

Saving the project with Project manager does nothing. 

Screenshot:
https://www.dropbox.com/s/a99kmyp4p4jbq2u/Sk%C3%A4rmklipp%202016-09-13%2010.13.42.png?dl=0

**Comment by jesseweed** [comment]
Hi @jonathan-dejong, is the folder by any change in your .gitignore? Do you see this with any other themes?

Atom adds a `status-ignored` class to ignored folders and files, and Seti only set the ignored styling to items with this class.

I think this is likely an issue with Atom and not in Seti itself. Feel free to re-open if you are able to pinpoint it to a issue that happens only with Seti.

Thanks!
