### ISSUE TITLE
Request: Icons for PowerShell

### ISSUE THREAD

**Issue by claudiospizzi** [jesseweed/seti-ui#336]
Hi

Since this icon set is available in Visual Studio Code, it would be amazing if you can provide icons for PowerShell core files:
Script files: `*.ps1`
Module definition files: `*.psd1`
Module content files: `*.psm1`

And maybe also for two special PowerShell XML file extensions:
Formatting files: `*.ps1xml`
CIM Cmdlet definitions: `*.cdxml`

And not to forget these two extensions completing the list:
Console File: `.psc1`
Session Configuration File: `.pssc`

The default icon for PowerShell is since version 5.0 this one:
![PowerShell](https://upload.wikimedia.org/wikipedia/commons/2/2f/PowerShell_5.0_icon.png)

**Comment by Glober777** [comment]
I'd like to second that.

**Comment by GHRoss** [comment]
I would like to third it.

**Comment by jesseweed** [comment]
This icon has now been added.
