### ISSUE TITLE
Window load time is 2.9x longer when using seti-ui

### ISSUE THREAD

**Issue by MobileSam** [jesseweed/seti-ui#338]
I don't know if there is anything that can be done to tweak the load speed, but when I activate seti-ui, the window load time jumps from 366ms to 1070ms. I'm on a mac with the El Capitan and uses the last version of both Atom and seti-ui (1.3.2). Here are the screenshots from Timecop.

With atom-black:
<img width="241" alt="screen shot 2016-09-15 at 08 39 52" src="https://cloud.githubusercontent.com/assets/1325796/18550040/0858d8b6-7b20-11e6-946a-97f343d38eb2.png">

With seti-ui:
<img width="224" alt="screen shot 2016-09-15 at 08 39 23" src="https://cloud.githubusercontent.com/assets/1325796/18550059/198ba0c8-7b20-11e6-8707-1565919de702.png">

**Comment by jesseweed** [comment]
Hi @MobileSam can you post the actual time for Seti? I show it as adding 107ms to startup time.

![screen shot 2016-12-03 at 2 33 26 pm](https://cloud.githubusercontent.com/assets/719964/20862645/81fd8314-b965-11e6-98de-3c7a2b3068c4.png)

**Comment by contentfree** [comment]
I'm on macOS Sierra and Timecop reports that seti-ui took more than 10,000 ms to activate!

![image](https://user-images.githubusercontent.com/10958/30657310-0559b06e-9dec-11e7-9b94-ab6a7aa023f6.png)

**Comment by jesseweed** [comment]
I think this issue has be resolved in recent updates, feel free to reopen if you disagree.
