### ISSUE TITLE
Change the size of Scrollbars and  Tabs

### ISSUE THREAD

**Issue by regmish** [jesseweed/seti-ui#340]
I have been using atom for more than 1 years, and I am loving it, and the recent update is cool but with two annoying things, I couldn't sort it out
`1.  Scrollbars are too wide , which makes the interface too ugly`
`2. Tabs sizes are too large that workspace  is squeezed`
![scrollbar](https://cloud.githubusercontent.com/assets/12388813/18828671/8c4cacfc-83f8-11e6-8b36-e3fa877e9b98.png)
![top_nav](https://cloud.githubusercontent.com/assets/12388813/18828670/8c4c1bb6-83f8-11e6-9ef4-c9f9e7590e93.png)

**Comment by shankarregmi** [comment]
+1

**Comment by jesseweed** [comment]
Scrollbar styles have been adjusted in 1.4 release.

Tab size can be adjusted by enabling "compact mode" in theme settings.

Feel free to re-open is you still have issues after updates.
