### ISSUE TITLE
"Display Ignored Files" setting has no effect

### ISSUE THREAD

**Issue by sharedprophet** [jesseweed/seti-ui#342]
With a recent update to seti-ui, it stopped showing ignored (in .gitignore) folders in my tree view, regardless of the "Display Ignored Files" setting. Also, my .gitignore has a setting to ignore a folder but explicitly include a specific subfolder of that folder, and set-ui has never handled theming that properly.

**Comment by xxmyjk** [comment]
+1

**Comment by xxmyjk** [comment]
@sharedprophet @jesseweed 

I don't know why the **tree-view** package was disabled by default. I enabled it and set  "Hide VSC Ignored Files" to false. Then the set-ui config worked well.
