### ISSUE TITLE
Seti-UI 1.3.2 causes issue with Autcomplete+ / atom-ternjs

### ISSUE THREAD

**Issue by jtm297** [jesseweed/seti-ui#346]
Notable issues:
The window is too wide compared to other UI themes.
There is some z-index issues with the entire Tree View.

![3313abae-90c8-11e6-9ccc-b23ba35178b8](https://cloud.githubusercontent.com/assets/794350/19362149/7b5f2876-9153-11e6-83c3-3fdf7907464f.png)

Switching to another UI theme resolves the issue and appropriately keeps the box within the confines of code.

**Comment by jesseweed** [comment]
@jtm297 some autocomplete updates were made in 1.4 release which hopefully should address your issue. Feel free to re-open if you still see it.
