### ISSUE TITLE
Highlight in suggestions hides params/returned value

### ISSUE THREAD

**Issue by riccardo1991** [jesseweed/seti-ui#358]
With Seti UI when I get suggestions, it is impossible to see the return type and params of the selected function.

<img width="693" alt="schermata 2016-11-15 alle 11 13 16" src="https://cloud.githubusercontent.com/assets/9364811/20301669/8a51f7c4-ab24-11e6-8f23-2909d89f4fbe.png">

**Comment by jesseweed** [comment]
This issue has been resolved.
