### ISSUE TITLE
Having seti-ui active forces tree-view to function as if it is active even though tree-view is disabled

### ISSUE THREAD

**Issue by nemchik** [jesseweed/seti-ui#361]
Referencing https://github.com/atom/tree-view/issues/994

I have the tree-view package disabled, however any time I enable the seti-ui theme the tree-view package functions as if it is enabled. The package remains disabled, but the `View > Togle Tree View` menu and the `Packages > Tree View` menu both remain active.

I have confirmed seti-ui is the cause by removing my .atom folder and starting with a fresh copy of Atom and installing only the seti-ui and seti-syntax. Simply switching from another theme to seti-ui forces the behavior. Reversing the behavior requires changing to another theme and then restarting Atom.

**Comment by YouKnowBagu** [comment]
I'm still a bit new to all of this, so forgive me if I'm way off base here.  It looks like the headers.coffee file activates and configs tree-view even if you have it disabled.  I ran a super quick test and added `if not atom.packages.isPackageDisabled('tree-view')` as the first line of headers.coffee, and it seemed to fix this.  Hope this is helpful!

**Comment by jesseweed** [comment]
This issue has been resolved.
