### ISSUE TITLE
Tabs Icon position issue

### ISSUE THREAD

**Issue by mfathirirhas** [jesseweed/seti-ui#362]
After latest update for Seti-UI today, I found out that it make the tabs icon position shift upside.
![image](https://cloud.githubusercontent.com/assets/11944811/20858582/8039fcd2-b97a-11e6-8c0a-184c0f354ef7.png)

**Comment by jesseweed** [comment]
@MFathirIrhas can you try a hard refresh of Atom (close and re-open)? Sometimes tabs get stuck in a weird state after updating.

**Comment by MFathirIrhas** [comment]
@jesseweed  I've restarted Atom, disable and re-enable, change back the theme, and even restarted pc, nothing work. The icons still shifted upside.

**Comment by jesseweed** [comment]
Hmm, okay thanks @MFathirIrhas! I'll see if I can repro. Can you confirm what version of Atom you're running?

**Comment by jesseweed** [comment]
Are you running the `file-icons` or similar plugin by any chance? If so, be sure to disable "Custom Icons" in settings for Seti UI as they conflict with each other.

**Comment by MFathirIrhas** [comment]
@jesseweed  I'm running version 1.12.6. I disable the Custom icon in Seti's settings, it solved the problem and icons gone. I hope it soon be fixed like it was before latest update. Thanks.

**Comment by jessy1092** [comment]
I have the same problem. I only install default theme and seti theme.

![ps3692](https://cloud.githubusercontent.com/assets/4408071/20867839/276266bc-ba88-11e6-9ba2-56cec74ee51e.jpg)

If I increase the line-height to 41px. It would solve this problem. I not sure the root cause.

![ps3693](https://cloud.githubusercontent.com/assets/4408071/20867856/8e676ef2-ba88-11e6-9577-f8ca44621570.jpg)

**Comment by jessy1092** [comment]
But it did not have problem on the macOS

<img width="1041" alt="2016-12-05 9 57 55" src="https://cloud.githubusercontent.com/assets/4408071/20871541/d9987f1c-bad1-11e6-8ed5-6478d601fe4d.png">


platform:
OS: macOS 10.12.1
Atom: 1.2.6
Seti: 1.4.0
Seti: 1.4.0

**Comment by craigbuckler** [comment]
The issue also affects my Windows 10 installation. Workaround fix: **File** > **Stylesheet...** then add:

```less
// fixes seti-ui icon position in tabs
atom-workspace.seti-icons .tab-bar .tab .title::before {
  line-height: 36px;
}
```

**Comment by hielfx** [comment]
Thanks @craigbuckler, it worked like a charm

**Comment by raworre** [comment]
@craigbuckler Thanks for the workaround. Fixed the issue perfectly.

**Comment by MFathirIrhas** [comment]
@craigbuckler  Thanks, work perfectly.

**Comment by odegraciajr** [comment]
@craigbuckler worked! Thanks!

**Comment by craigbuckler** [comment]
@TRiddle It's Atom's menu at the top.

**Comment by TRiddle** [comment]
@craigbuckler Thanks

**Comment by jesseweed** [comment]
So it sounds like this is only happening on Linux? I'll double check the fix doesn't break other platforms, and push it out as a bugfix release.

**Comment by hielfx** [comment]
@jesseweed It happened to me in Windows 10 too.

**Comment by jaredtm** [comment]
Happened to me on Windows 10 as well, employed @craigbuckler 's temp fix for now (worked well).  Thanks for the great theme @jesseweed .

**Comment by jesseweed** [comment]
The solutions I've seen so far all seem to fix the issue on Windows, but break on Mac.

I'll work on finding a solution that will work for both, but in the meantime, you can add this to user user stylesheet as a temporary fix on Windows:

```
// fixes seti-ui icon position in tabs
atom-workspace.seti-icons .tab-bar .tab .title::before {
  line-height: 36px;
}
```

**Comment by craigbuckler** [comment]
As a thought, `line-height` is a unit-less property because it's relative to the font size. Would this work on all platforms?...

```css
// fixes seti-ui icon position in tabs
atom-workspace.seti-icons .tab-bar .tab .title::before {
  line-height: 1.6;
}
```

**Comment by aeschli** [comment]
I've seen similar positioning issues on Windows in VSCode where we use the seti.woff font.
I tracked it down to [this change](https://github.com/jesseweed/seti-ui/commit/ca2330f7c1731ee91d30c61a126c7f807d34b3fa) in the 'cake.svg' icon. Removing the first path element (<path class="st0" d="M-351.2 98.1c-.4.1-.7.2-1.1.3v-134c.4.1.7.1 1.1.2V98.1z"/>) fixes the problem.

**Comment by Shockolate** [comment]
@craigbuckler et al 
Looks like the latest update has fixed this offset issue, causing the reverse :P
Removing that line returns it normal! Thanks again for adding that workaround.
Thanks for the support @jesseweed

**Comment by jesseweed** [comment]
This issue has been resolved.
