### ISSUE TITLE
artefacts when disabling scrollbar

### ISSUE THREAD

**Issue by rotsix** [jesseweed/seti-ui#367]
Hi guys,

Here is some informations about me : 

OS : archlinux 4.8.11-1
atom v1.12.6-1
seti-ui v1.4.0
brogrammer-syntax v1.0.0

------

I use minimap (v4.25.7)

Here is the problem : with minimap, i'm disabling scrollbar with this (styles.less)

```
atom-text-editor[with-minimap] .vertical-scrollbar,
atom-text-editor[with-minimap]::shadow .vertical-scrollbar {
  opacity: 0;
  width: 0;
}

atom-text-editor .horizontal-scrollbar,
atom-text-editor::shadow .horizontal-scrollbar {
	opacity: 0;
	width: 0;
}
```

But here is the problem, there is a small black area in the bottom right corner

http://img.piczel.tk/27753.png (full screen)
http://img.piczel.tk/27269.png (only the corner)

So, any idea about that ?

Thank you ! :+1: 

regards,
Piczel

**Comment by jesseweed** [comment]
@rotsix The screenshots do not seem to work, any chance you can re-post? Thanks!

**Comment by rotsix** [comment]
Hi, I come back to say that they disappeared.. I close !
