### ISSUE TITLE
Seti Tab Icons

### ISSUE THREAD

**Issue by mbarraz** [jesseweed/seti-ui#368]
The icons are cut in half in my tab space.

windows 10

**Comment by sim3001** [comment]
I also have this issue currently. Icons in the tab space are cut in half.

**Comment by mattalat** [comment]
I'm having the same issue. I'm on Windows 10 and the issue started within the past few weeks. 

#366 addresses this problem, for reference.

**Comment by maorefaeli** [comment]
i have the same on windows 10

**Comment by naknode** [comment]
I, too, am having this issue on Windows 7.

**Comment by deryost** [comment]
Same here with Windows 7

**Comment by undesconocido** [comment]
Same here, Win10.

**Comment by codyflynnNC** [comment]
Same issue here -win7

**Comment by tinyglowstudio** [comment]
I have a pull request in. I didn't realize I was duplicating this issue when I created issue #380.

**Comment by jesseweed** [comment]
Closing this as duplicate of #362.
