### ISSUE TITLE
Modify color of highlight when selecting

### ISSUE THREAD

**Issue by captain-awesome** [jesseweed/seti-ui#371]
Please advise on how to modify the color of the highlight when selecting text.

**Comment by tinyglowstudio** [comment]
This is a function of the theme, not of the UI. You'll want to change the CSS for atom-text-editor .selection .region in your theme's style.less file.

**Comment by T-Max100** [comment]
@tinyglowstudio I'm having this issue as well and I don't know where to begin fixing this. Are you suggesting I go to the style code for the theme seti-ui or go to styles.less found in .atom?

In the styles.less in .atom I don't have anything referring to .selection or .region. In the seti-ui theme styles folder I don't have anything like atom-text-editor.

**Comment by jesseweed** [comment]
Hi guys,
As mentioned, text selection color is handled by the syntax theme, not the ui them. However, you can edit in your user style sheet if you want to customize the color.
