### ISSUE TITLE
Misaligned Sections on Linux After New Install

### ISSUE THREAD

**Issue by john01dav** [jesseweed/seti-ui#373]
Hello,

I have just installed this UI theme on Atom running on Linux Mint, and, the upper-left area along with the tab text is misaligned:
![screenshot from 2016-12-26 16-52-12](https://cloud.githubusercontent.com/assets/3982497/21487296/abcc166e-cb8b-11e6-81bf-7aec6c3ab1cd.png)

As can be seen in that screenshot, the atom screenshot in the description is not the same as what I am seeing.

**Comment by jesseweed** [comment]
Closing this as duplicate of #362.
