### ISSUE TITLE
Show HTML5 icon for .html.erb files

### ISSUE THREAD

**Issue by ruppalsingh** [jesseweed/seti-ui#374]
I love the icons on this package (`atom-seti-icons`). However, on my Rails app, all of it looks like Ruby in the filetree. Would love it if `.html.erb` were shown with the HTML5 icon rather than the Ruby icon -- since they are primarily HTML files. I suggest it would look appropriate in a red shade for two reasons: it would differentiate it from the vanilla HTML5 files (which are orange) and, it would correctly brand `.html.erb` as a Ruby HTML file., as most other icon-sets do -- even the most popular one `file-icons`

**Comment by jesseweed** [comment]
This issue has been resolved.
