### ISSUE TITLE
Cannot resize folder view.

### ISSUE THREAD

**Issue by pronopenna** [jesseweed/seti-ui#388]
The left side bar(folder view) cannot resized when the theme is set as Seti.

Temporarily when I change other theme, then resize menu bar, that difference is maintained. 

 Please fix it 

 ( 'ㅅ' )

oh, My development environtment is follow next 

- Mac OS X El Capitan 10.11.6
- Atom 1.13.1 x64 
    - seti-ui 1.6.0

**Comment by jesseweed** [comment]
@pronopenna can you try and update to the latest Atom version and see if that helps? I'm also running El Capitan Atom 1.15 and do not have this problem.

Thanks!

**Comment by pronopenna** [comment]
After updates plugin, It's work fine. But when I open the file which is not
md file, resizing is disables  :p


I'm always thanks you for this useful & brilliant plug in  !
Have a nice day !
