### ISSUE TITLE
Icon scaling on Windows appears incorrect

### ISSUE THREAD

**Issue by lech** [jesseweed/seti-ui#397]
![scaling](https://cloud.githubusercontent.com/assets/396861/23584027/c2ac0460-011a-11e7-9ebf-8aa73d0b0d05.png)

I thought I was going crazy and posted an issue with @wyze believing it was a problem with the atom-seti-icons. He reports that it looks fine on OSX, however confirmed that on Windows the icon scaling appears incorrect and details are lost as you can see in the above screenshot. A good reference would be the shell icon that is just a grey indistinguishable block or config gear icons looking a bit chewed up.

**Comment by jesseweed** [comment]
Thanks @lech, will look into the issue. Closing this one as duplicate of #401, since it has more detail. Will update there any findings.

Cheers!

**Comment by lech** [comment]
Thanks, @jesseweed looking forward to a fix for it!
