### ISSUE TITLE
Updating to v1.6.1 -> Theme Color mismatch

### ISSUE THREAD

**Issue by kurtcarpenter** [jesseweed/seti-ui#399]
Having been using the blue theme color, I updated to 1.6.1 today, and on relaunch seti-ui was using the purple theme color. However, settings showed that blue was still selected.

Fixed this by selecting another color then going back to blue- just thought you should be aware of this tiny issue. Running on Windows 10, if that helps.

Thanks for an excellent theme! :)

EDIT: same thing occurred when updating to 1.7.0

**Comment by pdonias** [comment]
It happens to me quite often actually. Every once in a while, when I open Atom, all the buttons, checkboxes, etc. are blue even though it's set to "Red" in seti-ui settings. However, the tooltips are still red for some reason.

So then, I need to switch to another color and then back to red for everything to switch to red.

**Comment by jesseweed** [comment]
Thanks guys, I'll look into it. The update process I think is resetting the color preferences. I'll poke around and see if I can find a fix for it.

**Comment by jesseweed** [comment]
I believe this issue has been resolved. Free free to re-open if you disagree.
