### ISSUE TITLE
Close on left?

### ISSUE THREAD

**Issue by FezVrasta** [jesseweed/seti-ui#402]
Hi, it's annoying that the button to close the tabs is on the right instead of the left on macOS, can this be fixed please?

Thank you.

**Comment by jesseweed** [comment]
That's actually default Atom placement, and they way it's always been, so I don't think it's something I will change. However, it should be something you can tweak in your user styles if you really want it on the left.

Cheers!

**Comment by FezVrasta** [comment]
This is what I have with the default Atom theme:

![image](https://cloud.githubusercontent.com/assets/5382443/24238405/70f8ae22-0faa-11e7-8408-241c1b7e4d59.png)

**Comment by FezVrasta** [comment]
I already have `close-on-left` package but it doesn't work with your theme. I think this is something you should address in your theme directly, it's very annoying.
