### ISSUE TITLE
Uncaught TypeError opens console when switching projects

### ISSUE THREAD

**Issue by Duncank** [jesseweed/seti-ui#414]
I'm using the Project Viewer plugin to switch between projects, and everytime when I open Atom or switch to another project, the Chrome Console opens with the following error:

> [path to atom]\.atom\packages\seti-ui\lib\headers.coffee:6
> Uncaught (in promise) TypeError: Cannot read property 'roots' of null at file:///[path to atom]/.atom/packages/seti-ui/lib/headers.coffee:5:26
    at process._tickCallback (internal/process/next_tick.js:103:7)

## Environment
- **OS**: Windows 10, 64 bit;
- **Atom**: 1.16.0;
- **Seti UI**: 1.7.0

## Screenshot
![o16ind](https://cloud.githubusercontent.com/assets/719365/25064000/2c95dde6-21f1-11e7-82c6-73b3cef00265.jpg)

**Comment by jesseweed** [comment]
This should be fixed in the 1.9 release. Please let me know if you still experience the issue after updating. Thanks!
