### ISSUE TITLE
Tab icons cropped on version 1.7.0

### ISSUE THREAD

**Issue by Ninglin** [jesseweed/seti-ui#416]
Icons in the tab items are cropped in the latest version. Heres a screenshot:

![image](https://cloud.githubusercontent.com/assets/1248732/25236702/65b03f48-25e0-11e7-9600-b0543474784f.png)

**Comment by XJahdai** [comment]
There is a workaround described in this other thread

[](https://github.com/jesseweed/seti-ui/issues/362)

You can add:

`// fixes seti-ui icon position in tabs //MEXICANADA PARA ARREGLAR ICONOS
atom-workspace.seti-icons .tab-bar .tab .title::before {
  line-height: 36px;
}`
To your stylesheet and it will solve the problem

**Comment by Ninglin** [comment]
That solved it. Thank you very much.
