### ISSUE TITLE
Misplaced icons in tabs

### ISSUE THREAD

**Issue by RonnieDsouza** [jesseweed/seti-ui#417]
![setibug](https://cloud.githubusercontent.com/assets/24920297/25271488/efe8c9f2-26a1-11e7-954c-6d5eb47880c1.PNG)
the icons on the tabs are shifted up slightly. I restarted atom but it still persists.

**Comment by imrafg** [comment]
windows 10 temp fix -> https://github.com/jesseweed/seti-ui/issues/362

**Comment by CookeMoore** [comment]
craigbuckler commented on Dec 5, 2016
The issue also affects my Windows 10 installation. Workaround fix: File > Stylesheet... then add:

// fixes seti-ui icon position in tabs
atom-workspace.seti-icons .tab-bar .tab .title::before {
  line-height: 36px;
}

**Comment by jesseweed** [comment]
I believe this issue has been resolved. Free free to re-open if you disagree.
