### ISSUE TITLE
Icon: Please add a VueJS icon!

### ISSUE THREAD

**Issue by himynameisdave** [jesseweed/seti-ui#420]
Hi! Would be great if you could add a VueJS icon so that `seti-ui-icons` for Atom would show something better than the bars for VueJS files! Thanks!

<img width="192" alt="screen shot 2017-05-06 at 9 52 49 am" src="https://cloud.githubusercontent.com/assets/4298089/25774317/c95d1972-3241-11e7-9ffc-dcf9ca485e41.png">

**Comment by jesseweed** [comment]
Yes! Vue icon was added in the 1.8.0 release. Thanks @Hirse
