### ISSUE TITLE
Theme color reset after update

### ISSUE THREAD

**Issue by adumas37** [jesseweed/seti-ui#421]
Every time there is an update of the package, the colour of the theme come back to the default one (blue). When I go back into the theme settings, the color selected is the one I choosed (Red), and I need to choose another color to switch back to the one I want.

Thanks for the great theme btw :)

**Comment by milosmilikic** [comment]
I have similar issue. If I set some other syntax theme than seti-syntax, every time I re-open a project syntax theme is being reset to default atom theme. So, seti-ui just works properly with seti-syntax. For every other downloaded theme it's going back to default one.

**Comment by jesseweed** [comment]
I believe this issue has been resolved. Free free to re-open if you disagree.
