### ISSUE TITLE
gulpfile and gulpfile.babel missing .js extension in mapping.less

### ISSUE THREAD

**Issue by tamowicz** [jesseweed/seti-ui#422]
Hi!
Not sure if it's relevant for the project itself, but I noticed that VS Code is not picking the gulp icon for gulpfile.js. Easy fix for me was to add .js extension and it worked all right.

I know that It's an extension related issue but since it's based on your project I thought, I'll contribute at least this way.

Also adding npm icon for package.json might be worth considering, but that's another story.

Sorry for the 'informal' format..

**Comment by jesseweed** [comment]
Thanks @tamowicz I'll get those gulp changes in the next update!

I've debated adding npm icon to `package.json` but since it's also used for other things (with yarn for example) I decided to hold off on it.

**Comment by tamowicz** [comment]
Since yarn is basically based on npm registry, adding it's icon for package.json might not be such a bad idea. It's by far, the most ubiquitous use-case for this file.
