### ISSUE TITLE
Incorrect tree view rendering on Atom 1.17.0 & New extendable footer?

### ISSUE THREAD

**Issue by ZoneSix** [jesseweed/seti-ui#423]
The tree view doesn't look right to me on Atom 1.17.0. The styling just needs a bit of updating for the new version. (Bumped down the contrast a bit so it's easier to see the issue):
![atom_2017-05-18_17-07-22](https://cloud.githubusercontent.com/assets/8831008/26209357/e26f31d4-3bec-11e7-9ace-e5c0e14a9f50.png)

In this version of Atom, they also added an extendable footer. Though I'm not sure if it's an addition because of Linter. It looks like the default styling of Seti is applying ok to it. But it does look a little odd to me with the tabs and the table headers.
![atom_2017-05-18_17-15-00](https://cloud.githubusercontent.com/assets/8831008/26209756/f56c94ce-3bed-11e7-8462-1a0b626d0ec9.png)

EDIT: I looked into it a bit more. It seems like these are collapsible panels where you can have different panes open. And it looks like the tree view is a pane/tab now that can be moved around. Seti has a little of catching up to do. Good luck 👍

**Comment by jesseweed** [comment]
Yeah, a lot of UI updates have dropped recently! I have a 2.0 update in the works which will hopefully address most of the issues. Should be able to push it out sometime this week.

**Comment by jesseweed** [comment]
I think most "funkiness" has been address in the 1.9 update. However, the bottom dock still feels a little weird to me, so leaving this open to track that.

**Comment by jesseweed** [comment]
I believe this issue should be resolved. Feel free to re-open if you disagree.
