### ISSUE TITLE
Appears to break package updates via GUI

### ISSUE THREAD

**Issue by SpainTrain** [jesseweed/seti-ui#425]
See https://discuss.atom.io/t/solved-fetching-outdated-packages-and-themes-failed/39539/19

Also https://discuss.atom.io/t/solved-checking-for-package-updates-fails/40757/5

**Comment by henrydobson** [comment]
Can confirm. 

OS: Mac OS  10.12.3
Atom: 1.16.0
Seti Syntax: should have checked before but I believe 1.1.2
Seti UI: should have checked before but I believe 1.6.1

Uninstalling all Seti resolves update issue.

**Comment by jesseweed** [comment]
@henrydobson @SpainTrain  this should have been fixed in the v1.1.3 update of seti-syntax. Can you let me know if you still have the same problem after updating?

Thanks!

**Comment by jesseweed** [comment]
Assuming this is fixed, feel free to open if not.
