### ISSUE TITLE
icon for .toml files 

### ISSUE THREAD

**Issue by winuxue** [jesseweed/seti-ui#429]
Is it possible to associate the .toml files to the same icon as .config?
If you read the documentation (https://github.com/toml-lang/toml)
TOML aims to be a minimal configuration file format. So i think that icon is the best for this file extension.
**Horizons** uses this kind of configuration files, then it will be usefull for **Horizon** developers like me.

**Comment by jesseweed** [comment]
This has been added in the 1.9 release. Cheers!
