### ISSUE TITLE
Project Find Results Spacing is Off

### ISSUE THREAD

**Issue by contygm** [jesseweed/seti-ui#431]
<img width="644" alt="screen shot 2017-06-06 at 11 35 40 am" src="https://user-images.githubusercontent.com/19158002/26837799-5dd6f776-4aac-11e7-93bd-daf1ee34ee34.png">

**Comment by cuberoot** [comment]
I'm also having the same issue

**Comment by persac** [comment]
Duplicate of #427

**Comment by jesseweed** [comment]
Closing as dupe of #427. Fix coming shortly.
