### ISSUE TITLE
Icon for Clojure and Clojurescript

### ISSUE THREAD

**Issue by JayAndCatchFire** [jesseweed/seti-ui#435]
I'd like to request an icon for clojure and clojurescript files.  They can be the same icon for both.  I'm not picky.

**Comment by lil5** [comment]
<https://upload.wikimedia.org/wikipedia/commons/5/5d/Clojure_logo.svg>

working on it

**Comment by lil5** [comment]
<https://github.com/lil5/seti-ui/commit/b928bd945a188168fb8fd48019e277a077738451>

**Comment by JayAndCatchFire** [comment]
Thanks for catching edn as well.

**Comment by JayAndCatchFire** [comment]
I'm assuming this can be closed?

**Comment by lil5** [comment]
My fork has been merged so yes
