### ISSUE TITLE
DLang source file icon

### ISSUE THREAD

**Issue by TurkeyMan** [jesseweed/seti-ui#436]
There are icons included for a huge number of languages, including many languages that seem far more niche than D.
Please consider dropping a dlang icon in the mix?

**Comment by lil5** [comment]
@jesseweed

**Comment by TurkeyMan** [comment]
Should be fine, if it doesn't end out too wide given the second moon... (the 'D' is meant to be mars, the 2 circles are Mars's 2 moons). D language was originally named 'Mars' ;)

**Comment by lil5** [comment]
Due to slow release cycle and pull request activity, I'm not bothered to help out and have started using https://atom.io/packages/file-icons
As that was my reason for installing seti-ui

**Comment by jesseweed** [comment]
I believe this issue should be resolved. Feel free to re-open if you disagree.
