### ISSUE TITLE
Change git icons?

### ISSUE THREAD

**Issue by Leedehai** [jesseweed/seti-ui#437]
For example, .gitignore files are a convention of Git. GitHub is a git hosting service and private corporation, among many others, that use this convention. So I think it is more appropriate to use the git logo (https://git-scm.com) for .gitignore and other git-related file types.

More explanation: https://github.com/Microsoft/vscode/issues/28435

**Comment by jesseweed** [comment]
This should be fixed in the 1.9 release. Cheers!
