### ISSUE TITLE
Feature request: icon for Extended Backus–Naur form (EBNF) files

### ISSUE THREAD

**Issue by Leedehai** [jesseweed/seti-ui#438]
Hi. I know few people may have heard of *.ebnf files, but I still hope there is an icon for this. In Computer Science, these files are used to formally express programming language grammar.

https://en.wikipedia.org/wiki/Extended_Backus–Naur_form

Edit: I can just add it myself. But your README didn't provide what the canvas size of the icon should be..
Now that seti-ui is integrated with many other products I think the improvement better to done by you:)

**Comment by jesseweed** [comment]
Hello, I'm closing this due to not high enough demand. But feel free to open a pull request to add this if you would still like to see it.
