### ISSUE TITLE
ignored files are frequently showing up as dimmed rather than hidden.

### ISSUE THREAD

**Issue by ckot** [jesseweed/seti-ui#450]
I've finding that I need to, at least once a day, open up the seti-ui config in settings/themes and check the 'Displayed Ignored Files' box and then uncheck it in order to make the ignored files hidden again.

I have seti-ui 1.9.0 installed.  I have no idea if this is an issue with seti-ui itself, or an upstream Atom issue. Both of my Mac OS system (at home and at work) are running Atom 1.19.0 and are affected.

I *believe* this was only an an issue after upgrading to Atom 1.18.0, and the problem persists with 1.19.0

Atom    : 1.19.0
Electron: 1.6.9
Chrome  : 56.0.2924.87
Node    : 7.4.0

I can provide more details upon request.  I'm simply not sure what else to add.

**Comment by jesseweed** [comment]
I believe this issue should be resolved. Feel free to re-open if you disagree.
