### ISSUE TITLE
Differentiate .ts from .spec.ts files

### ISSUE THREAD

**Issue by alexgoldstone** [jesseweed/seti-ui#455]
An Angular application following recommended practices will contain a lot of **.ts** (for code) and **.spec.ts** (for tests) where the filenames will be the same other than those extensions.

Currently VS Code shows the 'TS' icon for both (image attached) which is technically correct but would be very useful if there was a differentiation between the two - even if just color. Quite often my filenames are long enough that the end of the filename cannot be seen and I'm reliant on the icons to identify which is which.

This request appears to be possible as noted [here](https://github.com/Microsoft/vscode/issues/28848#issuecomment-308969564).

<img width="226" alt="screen shot 2017-10-11 at 23 23 11" src="https://user-images.githubusercontent.com/540888/31469829-32cb3bda-aedb-11e7-80bc-8efeeb144989.png">

**Comment by smhxx** [comment]
Closed by #462 🎉
