### ISSUE TITLE
Hide tittle bar option didn't work

### ISSUE THREAD

**Issue by phithanh1230** [jesseweed/seti-ui#458]
i don't know why but nothing happens when i checked into Hide title bar option

**Comment by JoshuaM928** [comment]
One year late but the same thing is happening to me. Did you ever find a fix?

**Comment by jesseweed** [comment]
This option only applies to Mac OS version due to Electron settings and not being able to hide title on Windows. Feel free to re-open if you see this option now working on Mac.
