### ISSUE TITLE
Solarized-Seti-UI

### ISSUE THREAD

**Issue by turnerboy** [jesseweed/seti-ui#460]
Hi am a big fan of the Seti UI for Atom. Recently after downlading the lastest version of Atom 1.22.1 i was getting some errors(deprecations) with Solarized Seti-UI. The bottom navbar has become gray and so is the welcome screen. It also throws this error.

<img width="1280" alt="screen shot 2017-11-21 at 2 46 43 pm" src="https://user-images.githubusercontent.com/22258902/33064216-f681e876-ceca-11e7-84f9-56bd0badce66.png">
<img width="1015" alt="screen shot 2017-11-21 at 2 46 54 pm" src="https://user-images.githubusercontent.com/22258902/33064219-f815d698-ceca-11e7-8e6f-28350d42a500.png">

Can anyone fix this issue i would love to continue using it. **_Thanks in advance_**

**Comment by jesseweed** [comment]
Hi @turnerboy, this repo is actually only for the original seti-ui theme, you can file an issue with the solarized-seti-ui fork here: https://github.com/wwmyers/solarized-seti-ui

Thanks!
