### ISSUE TITLE
seti.woff broken: no symbols visible in VSCode

### ISSUE THREAD

**Issue by aeschli** [jesseweed/seti-ui#464]
Since the latest updates of seti, the seti.woff font no longer works in VSCode on Windows. No font characters are visible.

The problem is that the newly added `etherum.svg` has [some vertices](https://github.com/jesseweed/seti-ui/blob/16dc5ccb7db6329f99c20c75fc7b536965765a96/icons/ethereum.svg#L9) that are far off. That seems to mess up the font normalisation.

Removing the path and regenerating the font solves the problem.

**Comment by Mootly** [comment]
Also the cause of #467 (and all the dups thereof).
