### ISSUE TITLE
Versions 1.9.1 through 1.11.0 missing git tags

### ISSUE THREAD

**Issue by smhxx** [jesseweed/seti-ui#466]
Just wanted to point out that it appears versions 1.9.1-1.11.0 of `seti-ui` are not tagged on GitHub, causing apm/Atom to think that v1.9.0 is the most recent version. Probably just a matter of doing `git push origin --tags`, but thought I'd bring it up since it means these newer versions aren't currently being pushed out to users. 👍

**Comment by forestgagnon** [comment]
this repo seems 💀. @jesseweed?

**Comment by mati865** [comment]
His last post on Twitter was 1 week ago, probably being busy.

**Comment by jesseweed** [comment]
Hi guys, thanks for your patience! I've been busy with other stuff (and had some issues publishing after updating computers). But just published 1.10.0 which is the latest.

Cheers!
