### ISSUE TITLE
Is it possible to change background color to match syntax theme?

### ISSUE THREAD

**Issue by vityavv** [jesseweed/seti-ui#474]
I really like seti-ui but I recently made a new syntax theme with an orange-ish background and I was wondering if it was possible to change the background color of the components in the user stylesheet or in the settings of seti-ui, and if so, how one would go about doing it. [These are what I'm talking about](https://imgur.com/Y0qjCsv)

**Comment by jesseweed** [comment]
I think I'm going to close this for now. I'm not really sure a way to make the background colors dynamic while still working in the confines of the predefined theme colors.

If anybody has suggestions on an easier way to accomplish this, feel free to re-open.
