### ISSUE TITLE
Spacing in Side Bar

### ISSUE THREAD

**Issue by lozyy** [jesseweed/seti-ui#476]
Hello all,

After I updated to the new version of Seti UI the file icons were messed up.
After turning on Custom File Icons in settings, the side bar spaces each file greatly apart:
<img width="960" alt="capture" src="https://user-images.githubusercontent.com/35091064/36343650-e17a82ec-13dc-11e8-8620-fd333a73c83b.PNG">

I am assuming this is an update problem, thank you.

**Comment by 1337cookie** [comment]
I am experiencing the same problem.

**Comment by jesseweed** [comment]
Closing as duplicate of #467.
