### ISSUE TITLE
padding with custom icons

### ISSUE THREAD

**Issue by Rellek** [jesseweed/seti-ui#477]
Updated to 1.10.0 and now have a lot of additional padding in my file tree between each file.  Enabling Compact Mode didn't fix the issue, however when I uncheck Custom Icons, the additional padding goes away.  Will continue adjusting various settings to see what else I can uncover. 

EDIT:  Here is a screen cap in case it helps.  https://i.imgur.com/VHESc20.png

**Comment by Blastius** [comment]
Duplicate of #467

**Comment by Rellek** [comment]
Duplicate of #467, closing.
