### ISSUE TITLE
Issue in line space in left pane

### ISSUE THREAD

**Issue by khumair** [jesseweed/seti-ui#478]
Hello I am getting issue in left panel. where user can see list of folder and files. 
In my case Line space between files name is round about 3 to 4 lines.. 
how can resolve this issue ? Thanks in advance 

![atom issue](https://user-images.githubusercontent.com/10771320/36537336-7f2f2ff2-17d8-11e8-83a4-24c7bd8a3a9a.png)

**Comment by Mootly** [comment]
Duplicate of issue #467

**Comment by jesseweed** [comment]
This has been resolved in 1.11.0
