### ISSUE TITLE
Tree view has too much vertical spacing after updating seti-ui

### ISSUE THREAD

**Issue by RonyNasr** [jesseweed/seti-ui#481]
![image](https://user-images.githubusercontent.com/14307250/36725356-c214cc02-1bbe-11e8-90d7-877e17680fa5.png)
This only happens when I select Seti-ui 
seti-ui version: 1.10.0
seti-syntax version: 1.1.3
treeview version: 0.221.3
atom version: 1.24.0

**Comment by Fecony** [comment]
Same problem. 

Also "Core" in settings has much space
![seti](https://user-images.githubusercontent.com/36774784/36739342-56376f7e-1be8-11e8-8491-6136a9a4eafa.PNG)

**Comment by KnuTNatioN** [comment]
not only the treeview, the settings have this much space, too.

**Comment by Mootly** [comment]
Duplicate of #467

**Comment by jesseweed** [comment]
This is fixed in 1.11.0.
