### ISSUE TITLE
Selected search result has the same foreground and background color

### ISSUE THREAD

**Issue by stomvi** [jesseweed/seti-ui#485]
I am using seti-ui 1.10.0 along with atom 1.25.0. The selected search result has the same foreground and background color as the following screenshot shows:

![screen shot 2018-03-22 at 8 12 09 pm](https://user-images.githubusercontent.com/1802713/37769969-ccb01e12-2e0d-11e8-83ed-17b3eead1176.png)

Mac OS 10.13
atom 1.25.0
seti-ui 1.10.0

**Comment by stomvi** [comment]
Same situation in the search panel.
![screen shot 2018-03-23 at 10 55 16 am](https://user-images.githubusercontent.com/1802713/37809146-d3d2a928-2e88-11e8-88a2-3c34abf6e7a0.png)

**Comment by bavandrade** [comment]
This may be related to the following definitions in `styles/ui-variables.less`:

```less
@text-color-selected: @seti-primary;
@text-color-info: @seti-primary;
...
@background-color-selected: @seti-primary;
@background-color-info: @seti-primary;
```

The problem can also be seen in other places (blue button to the right is unreadable):

<img width="159" alt="Atom Minimap menu" src="https://user-images.githubusercontent.com/16383688/42102856-2157b9c6-7bbf-11e8-90f7-a799fc52e9c4.png">

Meanwhile, as a workaround, you can use a custom style to read the selected results of "Find in files":

```
atom-workspace.theme-seti-ui {
  .list-tree .match-line.selected:before {
    background-color: white;
  }
}
```

**Comment by jesseweed** [comment]
I believe this issue should be resolved. Feel free to re-open if you disagree.
