### ISSUE TITLE
Icon for prolog's .pro files

### ISSUE THREAD

**Issue by AlessioAtroni** [jesseweed/seti-ui#491]
I think it could be nice to have an icon for [prolog](https://en.wikipedia.org/wiki/Prolog)'s files, sadly it doesn't have a standard icon, sometimes it is represented by an owl which is the logo of it's most known implementation: [SWI-Prolog](https://en.wikipedia.org/wiki/SWI-Prolog).

![SWI-Prolog logo](http://www.swi-prolog.org/icons/swipl.png)

Prolog extensions were .pl and .pro but since perl also uses .pl files, .pro became the most used.

**Comment by orta** [comment]
Sure, happy to accept a PR
