### ISSUE TITLE
no icons on sidebar panel

### ISSUE THREAD

**Issue by mrtuvn** [jesseweed/seti-ui#50]
![ss](https://cloud.githubusercontent.com/assets/1908873/4855579/0f16c738-60a8-11e4-9b47-63f5c0d0a35c.png)
Hi devs team

I have installed seti_UI . Follow instruction but after setup , in panel sidebar not show icon file. You can see image above
I using Windows 8.1 , Sublime Text 3, with plugin SideBarEnhancements

**Comment by shmdhussain** [comment]
@jesseweed I am also not getting the icons for the file in sublime 3 #3083 build, see my screenshot, I installed using package control.

![screen shot 2015-09-20 at 11 58 39 am](https://cloud.githubusercontent.com/assets/4039657/9979783/1f36c5dc-5f8f-11e5-8aff-a2072714b6b1.png)

**Comment by edalee** [comment]
No icons in sidebar in Sublime 3 #3083 build.

**Comment by EvAlex** [comment]
:+1: No icons in sidebar in Sublime 3 #3083 build.

**Comment by uakob** [comment]
+!
No icons in sidebar in Sublime 3 #3083 build.
