### ISSUE TITLE
Icon for PlatformIO

### ISSUE THREAD

**Issue by ivankravets** [jesseweed/seti-ui#506]
Hey,

Thank you so much for a great addition to VSCode. We have PlatformIO IDE extension for VSCode ( https://marketplace.visualstudio.com/items?itemName=platformio.platformio-ide ) and would be thankful to see PlatformIO icon for our `platformio.ini` configuration file. 

We have it for Atom, see https://github.com/file-icons/atom/blob/master/lib/icons/.icondb.js#L167

How is difficult to add? What do you need from our side? SVG is attached. 
[platformio_logo.svg.zip](https://github.com/jesseweed/seti-ui/files/2299388/platformio_logo.svg.zip)

Thanks in advance!

**Comment by orta** [comment]
Open to adding this, there are instructions in the README 👍

**Comment by ivankravets** [comment]
@orta Could you help with this issue? I would be really thankful.

**Comment by orta** [comment]
Sure, here's [the link](https://github.com/jesseweed/seti-ui#adding-file-icons) directing how to add them

**Comment by ivankravets** [comment]
Please review https://github.com/jesseweed/seti-ui/pull/534

**Comment by orta** [comment]
Fixed by #534
