### ISSUE TITLE
R language icon is very large

### ISSUE THREAD

**Issue by aeschli** [jesseweed/seti-ui#507]
We use the woff font.

The R icon is exceeding its boundaries:
![image](https://user-images.githubusercontent.com/6461412/44854533-15145e00-ac69-11e8-84e5-fe00f8e3aecf.png)

https://github.com/jesseweed/seti-ui/blob/master/icons/R.svg

**Comment by yeahok** [comment]
I'll give this a try.

**Comment by DanTup** [comment]
@aeschli I noticed this was fixed in VS Code even though it's not fixed here yet. Is VS Code maintaining its own font now? I've opened https://github.com/jesseweed/seti-ui/pull/525 to add a Dart icon but I'm not sure if it's still being maintained here based on the dates of some of the open issues/PRs or in VS Code.

**Comment by aeschli** [comment]
We just made a patch for the R icon. See here: https://github.com/Microsoft/vscode/commit/542375c6d5d77970305c5aadeac26ea9469be5e0

**Comment by DanTup** [comment]
@aeschli If things aren't being maintained here, is it possible to contribute the new Dart icon into VS Code? My PR has all the files, though probably it'd need the R icon re-patching before committing to Code.

**Comment by aeschli** [comment]
We don't really want to branch off. There has been regular updates in the past, so I'd suggest we stay patient

**Comment by DanTup** [comment]
Understood, though it's been 5.5 months since this issue was opened and GH says the last change to master was 7 months ago 😔

**Comment by bergmeister** [comment]
@aeschli I would like to add an icon to `vscode` but seeing that this repo seems to not review PRs any more  is not great. What do you suggest?

**Comment by orta** [comment]
This is now merged 👍
