### ISSUE TITLE
Add same coloring as `.spec.js` to `.test.js`

### ISSUE THREAD

**Issue by garrettjstevens** [jesseweed/seti-ui#514]
Hello there,

Currently files with the `.spec.js` extension get the same icon as `.js` files, but a different color (orange instead of yellow). I'd like to propose that the `.test.js` extension be given the same colorization as `.spec.js` since popular testing frameworks like [Jest](https://jestjs.io/) treat those equivalently.

Relevant code (I think?):
https://github.com/jesseweed/seti-ui/blob/89175d7f9e0c70cd325b80a18a3c77fc8eb7c798/styles/components/icons/mapping.less#L156-L163

Thanks!

**Comment by orta** [comment]
This is in 👍

**Comment by garrettjstevens** [comment]
@orta are you referring to #530? That appears to only take care of the Typescript case, not the Javascript case.
