### ISSUE TITLE
TypeScript icon colors are inconsistent

### ISSUE THREAD

**Issue by misolori** [jesseweed/seti-ui#518]
Ref https://github.com/Microsoft/vscode/issues/64147

![img](https://user-images.githubusercontent.com/18474125/49339989-0cbf2b00-f67d-11e8-91f9-c3f43d8bee56.png)
> I think *.test.ts should definitely be yellow for consistency with the other... so that I can easily discriminate real source files and test files (I filed this issue because I'd prefer test which is more descriptive as a filename rather than spec, if it's not blue!).
> 
> Other icon themes generally seem to treat these two as the same.

**Comment by goenning** [comment]
I'd say that `spec.tsx` and `test.tsx` should also be yellow for the same reason. They're currently blue.
