### ISSUE TITLE
 Replace the java file icon with the old java cup icon

### ISSUE THREAD

**Issue by sanket-bhalerao** [jesseweed/seti-ui#538]
Issue Type: <b>Feature Request</b>

change java icon to the java cup icon.

VS Code version: Code - Insiders 1.37.0-insider (0bd57ac9efae79f9eb1aedc3818ebbb570b9bf6b, 2019-08-02T21:22:13.578Z)
OS version: Windows_NT x64 10.0.17134

![java icon](https://user-images.githubusercontent.com/9264813/62822610-97104500-bba3-11e9-9023-bea287c9d3c0.png)

**Comment by orta** [comment]
I'm pretty open to it - @nickzhums (I just grabbed you as someone who will know folks using Java in vs code) do you have an opinions on the default java file icon?

**Comment by nickzhums** [comment]
thanks for including me on this one. Let me also mention our engineering team here : @eskibear @CsCherrYY @jdneo @testforstephen @akaroml

**Comment by akaroml** [comment]
+1 to use the coffee cup. The current one is easily confused with an error indicator.

**Comment by nickzhums** [comment]
@orta We have discussed internally and decided we should go ahead with the icon replacement. How should we go about this?

**Comment by orta** [comment]
Someone should send a PR 👍🏻

**Comment by nickzhums** [comment]
@eskibear

**Comment by Eskibear** [comment]
So shall we use the cup above? It would look like below:

![image](https://user-images.githubusercontent.com/2351748/159660142-f6f7d082-3b23-47f8-842e-5c4fccaf3e02.png)

And do we want to change the color? E.g blue, which is also part of Java icon's color, effect below:

![image](https://user-images.githubusercontent.com/2351748/159661594-54e3a456-db09-4dbe-9598-ef54ff3dea7a.png)

**Comment by nickzhums** [comment]
tbh, blue seems a bit weird here - @orta do you have any suggestions? I'm ok with the red one (first picture)

**Comment by sanket-bhalerao** [comment]
could it be something like this?
![image](https://user-images.githubusercontent.com/9264813/159758381-f0e9b2fa-04cc-401e-9a86-4243b8484515.png)

**Comment by orta** [comment]
No suggestions on color, I don't use Java so I don't know what colour is culturally close. 

@sanket-bhalerao  - that's probably going to look out of placed and unbalanced compared to the other icons which are visually centered 👍🏻

**Comment by nickzhums** [comment]
@orta for the icon, do we need a 16x16 or 20x20 ?

**Comment by orta** [comment]
Recommendations are in the README: https://github.com/jesseweed/seti-ui#adding-file-icons and then compare with others for feel

**Comment by Eskibear** [comment]
We had a survey on Twitter: https://twitter.com/NickZhu9/status/1517053859025195008 . Turns out users are more fond of a simple J icon. So I just created a PR for it.  Below is the comparison with current behavior.

![image](https://user-images.githubusercontent.com/2351748/167578886-d4698f00-3e67-4140-8475-e50776e63707.png)
