### ISSUE TITLE
Use .ts icon for .tsx files

### ISSUE THREAD

**Issue by calebmer** [jesseweed/seti-ui#557]
At Airtable we use the `.tsx` extension for all of our files. Including all our backend files. Having the React icon for all of these files is a little bit jarring. Could we change the `.tsx` icon extension to be identical to the `.ts` icon? Or at least make it configurable.

The way we think about it is `.tsx` is version 2 of the TypeScript dialect so we should just use it everywhere instead of supporting multiple dialects of TypeScript.

**Comment by calebmer** [comment]
referred here from https://github.com/microsoft/vscode/issues/93347

**Comment by orta** [comment]
I'm open to this, yep 👍
