### ISSUE TITLE
Icon for Notebooks

### ISSUE THREAD

**Issue by misolori** [jesseweed/seti-ui#558]
With the introduction of Notebooks, there is a new file type being used:`ipynb`.  It would be nice if there was a file icon for this new file type since there is none:

![image](https://user-images.githubusercontent.com/35271042/77680870-c8325f80-6f51-11ea-9673-38391c399ba2.png)

One suggestion is to use a generic notebook icon (this is taken from the Microsoft Deign Language icon set):

![image](https://user-images.githubusercontent.com/35271042/77680926-db452f80-6f51-11ea-8363-bc4b402d3bcb.png)

**Comment by orta** [comment]
Agree, there might even already be a notebook-like icon in here already?

**Comment by misolori** [comment]
I didn't see any icon in the current set that matched, which one do you think would work for this?

**Comment by orta** [comment]
I didn't look - so if you don't see one, then there definitely isn't one! 🍡
