### ISSUE TITLE
Fall away css icon

### ISSUE THREAD

**Issue by chervyakovru** [jesseweed/seti-ui#573]
When adding VS Code setting for enable postCss highlight:

```
"files.associations": {
    "*.css": "postcss"
  },
```

Css file icon replaced with deafult file icon:
![image](https://user-images.githubusercontent.com/14909082/83881260-cc50d980-a759-11ea-8798-59b1658a5fca.png)
![image](https://user-images.githubusercontent.com/14909082/83881351-eb4f6b80-a759-11ea-94c5-69b1b707db9f.png)

I think the icon for css files should remain the same after change file associations

**Comment by orta** [comment]
this is probably a vscode bug 👍
