### ISSUE TITLE
.tsx (typescriptreact) should show React icon

### ISSUE THREAD

**Issue by mlntr** [jesseweed/seti-ui#610]
Following on from https://github.com/microsoft/vscode/issues/118162. Currently `.tsx` shows the regular `.ts` icon. Using the React icon instead will help distinguish between `.ts` & `.tsx` files more easily.
![image](https://user-images.githubusercontent.com/17552475/122648085-51b5ea80-d11f-11eb-824d-20d5c3c89b22.png)

Also IMO `*.test.ts` (and `*.spec.ts`) icon shouldn't be yellow as that's confusable with JS files (`*.test.js` uses orange which would be better)
![image](https://user-images.githubusercontent.com/17552475/122648141-a9545600-d11f-11eb-96d8-d2d3b9ac9a4d.png)

**Comment by zkldi** [comment]
> Also IMO *.test.ts (and *.spec.ts) icon shouldn't be yellow as that's confusable with JS files (*.test.js uses orange which would be better)

Just wrote a PR for this part under #611 as I was similarly confused by it.

**Comment by orta** [comment]
This is in
