### ISSUE TITLE
Display React icon for .tsx files

### ISSUE THREAD

**Issue by tjbulick** [jesseweed/seti-ui#620]
Hi
I saw a couple of issues with the same question (https://github.com/microsoft/vscode/issues/118162, https://github.com/jesseweed/seti-ui/issues/610), but see no progress so opening a new one
Also I saw people there saying that they use .tsx files in non-react projects (#557, https://github.com/microsoft/vscode/issues/93347), but this makes no sense since tsx is derived from JSX, and JSX itself is bound to React and can't be used in any other-than-react project.
The icon has already showed React previously, before this change https://github.com/jesseweed/seti-ui/pull/566 by @orta, and i guess that was reasonable.
Can we finally get back tsx showing React icon and don't confuse people?
I can submit a PR if there's no one who's in the context and is able to do it quickly
![Image 8-12-21 at 12 28 AM](https://user-images.githubusercontent.com/28315191/129106237-273657e9-279d-45e5-ab64-ab2d9a1742e4.jpg)

P.S. [Typescript clearly says that .tsx files have such extension because of JSX](https://www.typescriptlang.org/docs/handbook/jsx.html)

**Comment by orta** [comment]
> JSX itself is bound to React and can't be used in any other-than-react project.

This isn't really true, (preact, stencil, vue all have jsx support). I think the original reasoning for switching is fine, so we'll keep it as is.

**Comment by tjbulick** [comment]
> > JSX itself is bound to React and can't be used in any other-than-react project.
> 
> 
> 
> This isn't really true, (preact, stencil, vue all have jsx support). I think the original reasoning for switching is fine, so we'll keep it as is.

Okay this is not true, but wait, this is the most common use case though?
The analogy here would be that not all people write javascript in .js files, but we don't really care about them because they are the minority.

The same thing with tsx, most people write react + ts code in those files, and they want to see proper icon next to their files (including me).
Shouldn't we do a favor for the majority?

**Comment by tjbulick** [comment]
And furthermore, the extension of the file doesn't tell anything about its contents, so i may write any code inside of .js, .ts or .tsx. It rather serves to **indicate most used file format** (which is `typescriptreact` in our case), and any OS or IDE will highlight them as corresponding programming language. 

So i guess we should act in the interest of the vast majority of users.

**Comment by landisdesign** [comment]
> This isn't really true, (preact, stencil, vue all have jsx support). I think the original reasoning for switching is fine, so we'll keep it as is.

The only original reasoning I see if from #557:

> The way we [AirTable] think about it is .tsx is version 2 of the TypeScript dialect so we should just use it everywhere instead of supporting multiple dialects of TypeScript.

Does it really make more sense to say "TSX is TypeScript version 2.0" than "TSX is a TypeScript extension to JSX"? If so, shouldn't we look for a new icon for TypeScript 3, 4, 5...
