### ISSUE TITLE
New seti shell icon makes it looks like all files names start with underscore

### ISSUE THREAD

**Issue by aeschli** [jesseweed/seti-ui#625]
From https://github.com/microsoft/vscode/issues/131466

The new icon is a `$_`. When glancing through files, for me this makes it seem like all file names start with a `_`

<img width="310" alt="Screen Shot 2021-08-23 at 8 20 41 PM" src="https://user-images.githubusercontent.com/212305/130550791-22744fe1-2bf8-4499-a69e-b46d606f2776.png">

**Comment by misolori** [comment]
cc @orta @SNDST00M since this came from https://github.com/jesseweed/seti-ui/pull/616

**Comment by SNDST00M** [comment]
What if the `$` sign is adopted on its own?

**Comment by mattmc3** [comment]
The `$` on its own might be okay, but depending on how it looks, it could still suffer from the same issue the `$_` does - namely that icons comprised of symbols can too easily look like they are part of a file name. The iTerm2 app icon has a nice block cursor after the $ that might serve as a good alternative.

![iTerm2App](https://upload.wikimedia.org/wikipedia/commons/5/57/ITerm2_v3_icon.png)

**Comment by orta** [comment]
Yeah, all these ideas seem reasonable to me 👍🏻

**Comment by SNDST00M** [comment]
Tested it and I felt that `$` looked better than the `$[]` suggestion.
I'll open a pull for that
