### ISSUE TITLE
Threat .avif as image

### ISSUE THREAD

**Issue by efcoyote** [jesseweed/seti-ui#638]
It would be nice if [.avif](https://en.wikipedia.org/wiki/AVIF) files gets a mapping to `image`. They are supported in VSCode (Chrome) but does not have the correct icon.
![avif](https://user-images.githubusercontent.com/12809257/151695762-82de1184-9fbd-4ae6-847f-71d774169e8e.PNG)

**Comment by SethFalco** [comment]
For future reference, you can do something like:

> Closes #638

To have the PR automatically close the issue on merge.
Meanwhile, this has been completed, so it should be fine to close. :+1:

**Comment by efcoyote** [comment]
Thanks for the hint and sorry for not closing.
