### ISSUE TITLE
scroll-bar duplication when scrolling with code panel open.

### ISSUE THREAD

**Issue by AndalfTheBeard** [jesseweed/seti-ui#67]
![image](https://cloud.githubusercontent.com/assets/6903503/5409710/2120eab8-81e5-11e4-8f5d-5329345d8400.png)

This strange effect occurs only when scrolling a code panel and only affects the tree-view panel. Occurred on windows 8.1, atom version 0.152.0

**Comment by jesseweed** [comment]
Going to go ahead and close this out as it's pretty old, and haven't been able to duplicate.
