### ISSUE TITLE
Add _javascript_1 file icon to seti icon theme for test.mjs

### ISSUE THREAD

**Issue by desean1625** [jesseweed/seti-ui#697]
Can we add test.mjs extension to seti icon theme?

This file extension is the default for node js test runner.

It would be nice to have the same theming as the regular javascript for javascript modules.

https://github.com/microsoft/vscode/issues/210245

**Comment by gian1200** [comment]
Not only `test.mjs`, but add `.mjs` to all rules that have `.js`
https://github.com/jesseweed/seti-ui/blob/8fef6fa2992ff442158fde1928a3f079c910e999/styles/components/icons/mapping.less#L200

Also special cases such as `.spec.mjs`, `.test.mjs`, `.eslintrc.mjs`, new `eslint.config.mjs` flat config file, `webpack.{config,dev,prod,common}.mjs`, etc.
