### ISSUE TITLE
Where are the colors????

### ISSUE THREAD

**Issue by DemonKart** [jesseweed/seti-ui#70]
every file/document icon is gray for me now :/

**Comment by stevenhorner** [comment]
I had the same problem, which can be seen in the screenshot. Upgraded to latest version of Atom by doing the manual installation in Ubuntu and it now works again. Wish they had Atom in package management, forgot it didn't update without manually doing it.

![seti-ui](https://cloud.githubusercontent.com/assets/1365297/6059017/f9773ac4-ad24-11e4-872e-e2193f944c70.png)
