### ISSUE TITLE
Icon Spacing and Positioning is off

### ISSUE THREAD

**Issue by StinkyTofu** [jesseweed/seti-ui#78]
![screen shot 2015-01-08 at 3 27 26 pm](https://cloud.githubusercontent.com/assets/1767168/5672988/460b7552-974b-11e4-9daa-126e4f279208.png)
![screen shot 2015-01-08 at 3 29 07 pm](https://cloud.githubusercontent.com/assets/1767168/5672989/47635262-974b-11e4-903b-0351e6f06801.png)

**Comment by StinkyTofu** [comment]
That helped but I still get a few spacing issues when I first open atom.

![screen shot 2015-01-09 at 11 25 17 am](https://cloud.githubusercontent.com/assets/1767168/5685747/4e417152-97f2-11e4-9f7d-6063d10b9586.png)
![screen shot 2015-01-09 at 11 25 24 am](https://cloud.githubusercontent.com/assets/1767168/5685748/52ce12de-97f2-11e4-866e-c6a816a8cac5.png)

**Comment by markogresak** [comment]
I had the same issue, it's caused by [file-icons](https://github.com/DanBrooker/file-icons). I don't think the latter is needed, since this theme has most of the icons. But it would be nice if the two worked together without having to disable/uninstall file-icons.
