### ISSUE TITLE
FR: Preserve icon colors regardless of git status.

### ISSUE THREAD

**Issue by curtisblackwell** [jesseweed/seti-ui#79]
I find it harder to scan the tree because the icons change colors based on the associated file's git status.

The different colors that the icons have when there's no change in git status help make the tree much more scannable, but that goes out the window as things are now. Just changing the text's color is enough to scan git statuses, so changing the icons' colors doesn't improve UX.

I'd just override the styles with my stylesheet, but the specificity required is practically unmanageable, especially with the usage of `!important`s.

**Comment by asiahoe** [comment]
I had the [same request](https://github.com/jesseweed/seti-ui/issues/74), only I wasn't able to put it as succinctly, hehe. I really hope he considers it, now we have two requests!

**Comment by tsuflaj** [comment]
Better make it three.

**Comment by jesseweed** [comment]
I like that idea, will look into it for the next release.
