### ISSUE TITLE
0.174.0 deprecation notices

### ISSUE THREAD

**Issue by ilanbiala** [jesseweed/seti-ui#81]
Use the `atom-text-editor` tag instead of the `editor-colors` class.
Use the `atom-text-editor` tag instead of the `editor` class.
Use the selector `atom-text-editor[mini]` to select mini-editors.

These also appear in the seti-syntax theme.

**Comment by cgoggz56** [comment]
This is actually really simple to fix, it's really just a matter of find and replace. Issue number 1 and 3 are from the "editor" stylesheet. Hit Ctrl+f/Cmd+f and in the searchbox type "editor-colors" In the replace box type "atom-text-editor". 

The final issue is from the "lists" stylesheet. Follow the same steps as above, though replace 
"editor-colors" with ".editor". After all that is finished, close out of Atom and open it back up. If done correctly (and if memory served me correctly) you should no longer see the warnings relating to the theme.

**Comment by jesseweed** [comment]
Thanks for the heads up! I'll try and find some time to take a look this week (I have several other issues I want to try and get fixes in for as well).

**Comment by cgoggz56** [comment]
No problem, I'm glad to help out. By the way, awesome theme! Good work!

**Comment by tmn** [comment]
I submitted a PR on this one #82

**Comment by ilanbiala** [comment]
Still getting this in 0.176.0
```
seti-syntax
index.less
Use the `atom-text-editor` tag instead of the `editor-colors` class.
Use the `atom-text-editor` tag instead of the `editor` class.
Use the selector `atom-text-editor[mini]` to select mini-editors.
```
@jesseweed is a fix in progress?

**Comment by jesseweed** [comment]
@ilanbiala those deprecation errors actually relate to the seti-syntax package, and there's a bug filed on it already. I'm closing this as resolved since Atom no longer complains about seti-ui.
