### ISSUE TITLE
Request: A light version of Seti

### ISSUE THREAD

**Issue by jeffschwartz** [jesseweed/seti-ui#84]
So we can flip between the dark and the list UIs when we want to alter the contrast. Sort of like how we can use the Solarized UI.

**Comment by jesseweed** [comment]
@jeffschwartz I actually have [Yeti UI](https://atom.io/themes/yeti-ui) that was supposed to be a light version of Seti. It's a WIP though and I'm totally happy with it (and also a bit behind on updates).

I hope to get a lighter version out at some point, in the meantime you can try your luck with Yeti.

Cheers!
