### ISSUE TITLE
UI issue after update to 0.6.2

### ISSUE THREAD

**Issue by julienpa** [jesseweed/seti-ui#85]
Look what's going on after latest update (restarted Atom twice after it):
![screen](https://cloud.githubusercontent.com/assets/4720300/5916517/6ff79a5a-a612-11e4-8cc1-adb88fe11e87.jpg)

**Comment by Bert-Proesmans** [comment]
I have the same problem with the same version

**Comment by julienpa** [comment]
The update of Seti-ui came at the same time as Atom 0.176.
Maybe both are related?

**Comment by quicoto** [comment]
Sale here :(

**Comment by jaffacake** [comment]
I've got the same issue on 0.175

**Comment by williamboman** [comment]
+1

![](http://i.imgur.com/tOp2TMl.png)

On `Atom 0.176.0` & `seti-ui 0.6.2`.

**Comment by hubwub** [comment]
I don't know if this is a permanent solution for this issue. However, I rolled back tabs.less to an older version 10428aac2d536e3c3e3b3afdf2ad751f32e6e66 before one of the latest commits f22bba617c33333e750407f3f5545ec2d0700cda.

![](https://i.imgur.com/9u9mbRD.png)

**Comment by williamtrennem** [comment]
Same problem

**Comment by eswat2** [comment]
Same problem, applied suggested fix for tabs.less in order to make it usable -- thanks @hubwub

**Comment by middric** [comment]
Offending commit: https://github.com/jesseweed/seti-ui/commit/f22bba617c33333e750407f3f5545ec2d0700cda

**Comment by kupoback** [comment]
How do you roll back a commit @hubwub

**Comment by jonathandelgado** [comment]
@kupoback `apm rm seti-ui && apm install seti-ui@0.6.1`

**Comment by kupoback** [comment]
Thank you @jonathandelgado That worked!

**Comment by pmros** [comment]
I suppose this issue will be solved in set-ui 0.6.3. When will it be released?

**Comment by jesseweed** [comment]
Sorry guys, don't know what the deal is. I changed the tabs to fix the deprecation warnings Atom was throwing (they changed the class names of the tabs). I tested on my home machine and it was fine, but I just updated my work machine and I'm seeing the same issue as the rest of you. I'll update to include both the new and old class names. Stand by...

**Comment by williamboman** [comment]
@jesseweed Sweet, :+1:.

I would've PR'd a fix but been busy at work for ~12 hours :).

**Comment by jesseweed** [comment]
Pushed 0.6.3 update, should fix it. However my Atom is failing to check for updates so I can test the production version. Could somebody else give it a shot and let me know if 0.6.3 solved the problem?

**Comment by wesbland** [comment]
Looks good here.

**Comment by eswat2** [comment]
yeap, appears to work properly after updating to 0.6.3

**Comment by williamboman** [comment]
Looks good on `seti-ui 0.6.3` `atom 0.176.0`.

**Comment by Ventajou** [comment]
Thanks for fixing this so quickly, I really enjoy this theme.

**Comment by jeffschwartz** [comment]
works for me 2

**Comment by jesseweed** [comment]
Confirmed working in latest update.
