### ISSUE TITLE
Tabs issues with v0.6.2 

### ISSUE THREAD

**Issue by jeffschwartz** [jesseweed/seti-ui#89]
When switching theme to seti-ui 0.6.2 the tabs are almost impossible to see:
![set-ui_tabs](https://cloud.githubusercontent.com/assets/271288/5921134/b6fefb30-a60f-11e4-9b0c-dd4cce9610c1.png)
.

**Comment by AntouanK** [comment]
Check #85

**Comment by TerrenceLJones** [comment]
:+1:

**Comment by jesseweed** [comment]
Closing as duplicate of #85.
