### ISSUE TITLE
tabs style

### ISSUE THREAD

**Issue by leofle** [jesseweed/seti-ui#90]
after installing the update of seti 0.6.2 on atom 0.176.0 the tabs are not properly styled.

![screenshot 2015-01-27 20 42 42](https://cloud.githubusercontent.com/assets/2674606/5924545/597dbc84-a665-11e4-9bdb-080f456d2201.JPG)

**Comment by send2moran** [comment]
+1

**Comment by judahstevenson** [comment]
I'm experiencing this bug as well, immediately after the updates.

**Comment by jesseweed** [comment]
Closing as duplicate of #85.
