### ISSUE TITLE
Issue after update 0.6.3

### ISSUE THREAD

**Issue by bhhaskin** [jesseweed/seti-ui#91]
Having an issue after update to 0.6.3 it could a possible issue with file-icons DanBrooker/file-icons#99

![image](https://cloud.githubusercontent.com/assets/4709778/5926263/a927e2ce-a61e-11e4-9c6a-a017e4bb7d7d.png)

Atom: 0.176.0

**Comment by hubwub** [comment]
This issue is similar to https://github.com/jesseweed/seti-ui/issues/78 which existed before the 0.6.3 update.

**Comment by jesseweed** [comment]
Closing as duplicate of #78
