### ISSUE TITLE
Atom 0.136.0 (Windows)

### ISSUE THREAD

**Issue by andriyanputra** [jesseweed/seti-ui#92]
I just started using atom. I tried to use seti in atom version 0.136.0. The installation is doing well but after I tried to change the theme, did not go so well.  Here's my screenshot..
![err1](https://cloud.githubusercontent.com/assets/5051242/5960248/9f38de82-a806-11e4-911d-052a2ae66e3f.JPG)

![err2](https://cloud.githubusercontent.com/assets/5051242/5960250/a17c9ba2-a806-11e4-824e-e65866368b71.JPG)
I'm using last update of seti ui.
if anyone can help, I really appreciate it. Thanks

**Comment by jesseweed** [comment]
@andriyanputra can check to make sure you have the latest version of Atom installed? I believe 0.176.0 should be the latest. Let me know if that doesn't fix it.

**Comment by andriyanputra** [comment]
@jesseweed ok, thanks for your advice. :)
