### ISSUE TITLE
"Selected" color looks muted compared to "default"

### ISSUE THREAD

**Issue by nicktimko** [jesseweed/seti-ui#94]
I was getting confused if I was searching Packages or Themes because the active color is not what I'd expect:

![image](https://cloud.githubusercontent.com/assets/5297556/5996477/fd30ffb8-aa6f-11e4-96f0-d1035c31e287.png)

Other "selected" things, e.g. the settings tabs on the sidebar are active-blue, but not with the button group.

**Comment by jelmerdemaat** [comment]
I have the same problem with the searchfield, where the search options (case sensitivity, regex, ...) look enabled, when they are actually disabled.
In other words, in the following screenshot, the blue of the search filter buttons should be grey, and the grey should be blue:

![screenshot 2015-02-10 13 39 34](https://cloud.githubusercontent.com/assets/942560/6127384/7c248f68-b12a-11e4-9549-285f11e6acda.png)

**Comment by jesseweed** [comment]
I'll try and take a look at this this week. I actually haven't done much of any work on the settings area since they added the styles to that. Will put tweaking the interface elements next up on the roadmap).
