### ISSUE TITLE
Separate seti-ui icons

### ISSUE THREAD

**Issue by Victorystick** [jesseweed/seti-ui#95]
Have you considered making the custom file icons a separate package? While there is a file-icons package, there aren't as many icons. I'd prefer to use the Seti UI icons, but with another UI theme. I don't think there is anything preventing the icons from being used outside of Seti UI, is there?

**Comment by sammex** [comment]
This is a very good idea, but the colors of the icons could be a problem. So it could be better to make this in a separated configure file... Sounds like fun! :D

**Comment by jesseweed** [comment]
It's an interesting idea, but as @sammex mentioned, the icon colors could be tricky. It's probably not something I will do any time soon, but anybody can feel free to fork it and create an icon package out of it.
